<?php

?>
<div class="section-wrapper mg-t-20">
          
          
          <div class="pagination-wrapper justify-content-between">
           <?php  if($this->pageCount > 0 ):?>
            <ul class="pagination mg-b-0">
           
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Last">
                  <i class="fa fa-angle-double-left"></i>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <i class="fa fa-angle-left"></i>
                </a>
              </li>
            </ul>

            <ul class="pagination mg-b-0">
              <li class="page-item"><a class="page-link" href="#">11</a></li>
              <li class="page-item active"><a class="page-link" href="#">12</a></li>
              <li class="page-item"><a class="page-link hidden-xs-down" href="#">13</a></li>
              <li class="page-item"><a class="page-link hidden-xs-down" href="#">14</a></li>
              <li class="page-item"><a class="page-link hidden-xs-down" href="#">15</a></li>
            </ul>

            <ul class="pagination mg-b-0">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <i class="fa fa-angle-right"></i>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Last">
                  <i class="fa fa-angle-double-right"></i>
                </a>
              </li>
            </ul>
            <?php endif; ?>
          </div><!-- pagination-wrapper -->
        </div><!-- section-wrapper -->