<?php

namespace DoctrineORMModule\Proxy\__CG__\Shop\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cart extends \Shop\Entity\Cart implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'id', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'cartItems', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'cartUid', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'isSettled', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'user', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'createdOn', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'updatedOn', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'isUseBilling'];
        }

        return ['__isInitialized__', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'id', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'cartItems', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'cartUid', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'isSettled', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'user', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'createdOn', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'updatedOn', '' . "\0" . 'Shop\\Entity\\Cart' . "\0" . 'isUseBilling'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cart $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCartItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartItems', []);

        return parent::getCartItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getCartUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartUid', []);

        return parent::getCartUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSettled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSettled', []);

        return parent::getIsSettled();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function addCartItems(\Shop\Entity\CartItems $cartitem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartItems', [$cartitem]);

        return parent::addCartItems($cartitem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCartItems(\Shop\Entity\CartItems $cartItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCartItems', [$cartItem]);

        return parent::removeCartItems($cartItem);
    }

    /**
     * {@inheritDoc}
     */
    public function setCartUid($cartUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartUid', [$cartUid]);

        return parent::setCartUid($cartUid);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSettled($isSettled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSettled', [$isSettled]);

        return parent::setIsSettled($isSettled);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUseBilling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUseBilling', []);

        return parent::getIsUseBilling();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUseBilling($isUseBilling)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUseBilling', [$isUseBilling]);

        return parent::setIsUseBilling($isUseBilling);
    }

}
