<?php

namespace DoctrineORMModule\Proxy\__CG__\Transaction\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \Transaction\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'invoiceUid', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'cart', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'transaction', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'invoiceStatus', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'dueDate', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'paymentMethod'];
        }

        return ['__isInitialized__', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'invoiceUid', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'cart', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'transaction', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'invoiceStatus', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'dueDate', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Transaction\\Entity\\Invoice' . "\0" . 'paymentMethod'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceUid', []);

        return parent::getInvoiceUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCart', []);

        return parent::getCart();
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransaction', []);

        return parent::getTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceStatus', []);

        return parent::getInvoiceStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDate', []);

        return parent::getDueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceUid($invoiceUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceUid', [$invoiceUid]);

        return parent::setInvoiceUid($invoiceUid);
    }

    /**
     * {@inheritDoc}
     */
    public function setCart($cart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCart', [$cart]);

        return parent::setCart($cart);
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\Transaction\Entity\Transaction $transaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', [$transaction]);

        return parent::addTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransaction(\Transaction\Entity\Transaction $transaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransaction', [$transaction]);

        return parent::removeTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceStatus($invoiceStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceStatus', [$invoiceStatus]);

        return parent::setInvoiceStatus($invoiceStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function setDueDate($dueDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDueDate', [$dueDate]);

        return parent::setDueDate($dueDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

}
