<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Training\Module'                        => __DIR__ . '/Module.php',
    'Training\Controller\TrainingController' => __DIR__ . '/src/Training/Controller/TrainingController.php',
    'TrainingTest\Framework\TestCase'        => __DIR__ . '/tests/Training/Framework/TestCase.php',
    'TrainingTest\SampleTest'                => __DIR__ . '/tests/Training/SampleTest.php',
);
