<?php
echo $this->headtitle("View Training");
// $this->headLink()->prependStylesheet($this->basePath('wasabi/css/wasabi.gritter.css'))
// ->prependStylesheet($this->basePath('wasabi/css/wasabi.modal.css'))
// ->prependStylesheet($this->basePath('wasabi/css/wasabi.suggest.css'))
// ->prependStylesheet($this->basePath('wasabi/css/wasabi.wizard.css'));
?>

<div class="row">
	<div class="col-md-9">
		<div class="panel panel-inverse">
			<!-- begin panel-heading -->
			<div class="panel-heading">
				<div class="panel-heading-btn">
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a> <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a> <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
				</div>
				<h4 class="panel-title">Active Training</h4>
			</div>
			<!-- end panel-heading -->
			<!-- begin panel-body -->
			<div class="panel-body">
				<?php
				// 		var_dump($trainings);
				if (count($trainings) > 0) : ?>
					<table id="data-table-default " class="table table-striped table-bordered table-responsive">
						<thead>
							<tr>


								<th class="text-nowrap">Training UID</th>
								<th width="1%" data-orderable="false"></th>
								<th class="text-nowrap">Details</th>
								<th class="text-nowrap">Created On </th>
								<!-- 						<th class="text-nowrap">Platform(s)</th> -->
								<!-- 						<th class="text-nowrap">Engine version</th> -->
								<th class="text-nowrap"></th>
							</tr>
						</thead>

						<tbody>
							<?php foreach ($trainings as $training) :
								// 					var_dump($training);
								$json = json_encode(array(
									"data" => $training["trainingUid"]
								));
							?>
								<tr class="gradeU">
									<td><?php echo strtoupper($training["trainingUid"]) ?></td>
									<td class="with-img"><img src="<?php echo $this->imageHelper($training["image"]) ?>" class="img-rounded height-30" /></td>
									<td><?php echo ($training["trainingTopic"] != NULL ? $training["trainingTopic"] : "") ?></td>
									<td><?php echo $this->dateformat($training["createdOn"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?></td>

									<td><a data-json=<?= $json ?> id="sending_data_button" data-href="<?php echo $this->url("bbmintraining/default", array("action" => "premanage")) ?>" class="btn btn-default btn-block ajax_element">MANAGE</a></td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				<?php endif; ?>
			</div>
			<!-- end panel-body -->
		</div>
	</div>
</div>
<?php 
echo $this->inlineScript()
// ->appendFile($this->basePath('/lib/jquery/js/jquery.js'))
->appendFile($this->basePath('wasabi/js/wasabi.gritter.js'))
	->appendFile($this->basePath('wasabi/js/wasabi.suggest.js'))
	->appendFile($this->basePath('wasabi/js/wasabilib.min.js'))
	;
?>
