<?php
echo $this->headtitle("Manage Category");

?>
<div id="content">


	<div class="row">
		<!-- begin col-4 -->
		<div class="col-xl-4 col-lg-6">
			<!-- begin card -->
			<div class="col-xl-12 col-lg-6">
				<!-- begin widget-list -->
				<div class="m-b-10 f-s-10 m-t-10">
					<a href="#modal-widget-list"
						class="pull-right f-s-10 text-grey-darker m-r-3 f-w-700"
						data-toggle="modal">source code</a> <b class="text-inverse">WIDGET
						LIST</b>
				</div>
				<div class="widget-list widget-list-rounded m-b-30" data-id="widget">
					<!-- begin widget-list-item -->
					<div class="widget-list-item">
						<div class="widget-list-media">
							<img src="..\assets\img\user\user-12.jpeg" alt="" class="rounded">
						</div>
						<div class="widget-list-content">
							<h4 class="widget-list-title">Christopher Struth</h4>
							<p class="widget-list-desc">Bank Transfer</p>
						</div>
						<div class="widget-list-action">
							<a href="#" data-toggle="dropdown" class="text-muted pull-right"><i
								class="fa fa-ellipsis-h f-s-14"></i></a>
							<div class="dropdown-menu dropdown-menu-right">
								<a href="#" class="dropdown-item">Option 1</a> <a href="#"
									class="dropdown-item">Option 2</a> <a href="#"
									class="dropdown-item">Option 3</a>
								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item">Option 4</a>
							</div>
						</div>
					</div>
					<!-- end widget-list-item -->
					<!-- begin widget-list-item -->
					<div class="widget-list-item">
						<div class="widget-list-media">
							<img src="..\assets\img\user\user-13.jpeg" alt="" class="rounded">
						</div>
						<div class="widget-list-content">
							<h4 class="widget-list-title">Janie Flowers</h4>
							<p class="widget-list-desc">Bank Transfer</p>
						</div>
						<div class="widget-list-action">
							<a href="#" data-toggle="dropdown" class="text-muted pull-right"><i
								class="fa fa-ellipsis-h f-s-14"></i></a>
							<div class="dropdown-menu dropdown-menu-right">
								<a href="#" class="dropdown-item">Option 1</a> <a href="#"
									class="dropdown-item">Option 2</a> <a href="#"
									class="dropdown-item">Option 3</a>
								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item">Option 4</a>
							</div>
						</div>
					</div>
					<!-- end widget-list-item -->
					<!-- begin widget-list-item -->
					<div class="widget-list-item">
						<div class="widget-list-media">
							<img src="..\assets\img\user\user-14.jpeg" alt="" class="rounded">
						</div>
						<div class="widget-list-content">
							<h4 class="widget-list-title">Janie Flowers</h4>
							<p class="widget-list-desc">Bank Transfer</p>
						</div>
						<div class="widget-list-action">
							<a href="#" data-toggle="dropdown" class="text-muted pull-right"><i
								class="fa fa-ellipsis-h f-s-14"></i></a>
							<div class="dropdown-menu dropdown-menu-right">
								<a href="#" class="dropdown-item">Option 1</a> <a href="#"
									class="dropdown-item">Option 2</a> <a href="#"
									class="dropdown-item">Option 3</a>
								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item">Option 4</a>
							</div>
						</div>
					</div>
					<!-- end widget-list-item -->
				</div>
				<!-- end widget-list -->
			</div>
			<!-- end card -->
		</div>
		<!-- end col-4 -->
		<!-- end col-4 -->
		<!-- begin col-4 -->
		<div class="col-xl-4 col-lg-6">
			<!-- begin card -->
			<div class="card border-0 bg-dark text-white mb-3">
				<!-- begin card-body -->
				<div class="card-body">
					<!-- begin title -->
					<div class="mb-3 text-grey">
						<b>TOP PRODUCTS BY UNITS SOLD</b> <span class="ml-2"><i
							class="fa fa-info-circle" data-toggle="popover"
							data-trigger="hover" data-title="Top products with units sold"
							data-placement="top"
							data-content="Products with the most individual units sold. Includes orders from all sales channels."></i></span>
					</div>
					<!-- end title -->
					<!-- begin product -->
					<div class="d-flex align-items-center m-b-15">
						<div class="widget-img rounded-lg width-30 m-r-10 bg-white p-3">
							<div class="h-100 w-100"
								style="background: url(../assets/img/product/product-8.jpeg) center no-repeat; background-size: auto 100%;"></div>
						</div>
						<div class="text-truncate">
							<div>Apple iPhone XR (2019)</div>
							<div class="text-grey">$799.00</div>
						</div>
						<div class="ml-auto text-center">
							<div class="f-s-13">
								<span data-animation="number" data-value="195">0</span>
							</div>
							<div class="text-grey f-s-10">sold</div>
						</div>
					</div>
					<!-- end product -->
					<!-- begin product -->
					<div class="d-flex align-items-center m-b-15">
						<div class="widget-img rounded-lg width-30 m-r-10 bg-white p-3">
							<div class="h-100 w-100"
								style="background: url(../assets/img/product/product-9.jpeg) center no-repeat; background-size: auto 100%;"></div>
						</div>
						<div class="text-truncate">
							<div>Apple iPhone XS (2019)</div>
							<div class="text-grey">$1,199.00</div>
						</div>
						<div class="ml-auto text-center">
							<div class="f-s-13">
								<span data-animation="number" data-value="185">0</span>
							</div>
							<div class="text-grey f-s-10">sold</div>
						</div>
					</div>
					<!-- end product -->
					<!-- begin product -->
					<div class="d-flex align-items-center m-b-15">
						<div class="widget-img rounded-lg width-30 m-r-10 bg-white p-3">
							<div class="h-100 w-100"
								style="background: url(../assets/img/product/product-10.jpeg) center no-repeat; background-size: auto 100%;"></div>
						</div>
						<div class="text-truncate">
							<div>Apple iPhone XS Max (2019)</div>
							<div class="text-grey">$3,399</div>
						</div>
						<div class="ml-auto text-center">
							<div class="f-s-13">
								<span data-animation="number" data-value="129">0</span>
							</div>
							<div class="text-grey f-s-10">sold</div>
						</div>
					</div>
					<!-- end product -->
					<!-- begin product -->
					<div class="d-flex align-items-center m-b-15">
						<div class="widget-img rounded-lg width-30 m-r-10 bg-white p-3">
							<div class="h-100 w-100"
								style="background: url(../assets/img/product/product-11.jpeg) center no-repeat; background-size: auto 100%;"></div>
						</div>
						<div class="text-truncate">
							<div>Huawei Y5 (2019)</div>
							<div class="text-grey">$99.00</div>
						</div>
						<div class="ml-auto text-center">
							<div class="f-s-13">
								<span data-animation="number" data-value="96">0</span>
							</div>
							<div class="text-grey f-s-10">sold</div>
						</div>
					</div>
					<!-- end product -->
					<!-- begin product -->
					<div class="d-flex align-items-center">
						<div class="widget-img rounded-lg width-30 m-r-10 bg-white p-3">
							<div class="h-100 w-100"
								style="background: url(../assets/img/product/product-12.jpeg) center no-repeat; background-size: auto 100%;"></div>
						</div>
						<div class="text-truncate">
							<div>Huawei Nova 4 (2019)</div>
							<div class="text-grey">$499.00</div>
						</div>
						<div class="ml-auto text-center">
							<div class="f-s-13">
								<span data-animation="number" data-value="55">0</span>
							</div>
							<div class="text-grey f-s-10">sold</div>
						</div>
					</div>
					<!-- end product -->
				</div>
				<!-- end card-body -->
			</div>
			<!-- end card -->
		</div>
		<!-- end col-4 -->
		<!-- begin col-4 -->
		<div class="col-xl-4 col-lg-6">
			<!-- begin card -->
			<div class="card border-0 bg-dark text-white mb-3">
				<!-- begin card-body -->
				<div class="card-body">
					<!-- begin title -->
					<div class="mb-3 text-grey">
						<b>MARKETING CAMPAIGN</b> <span class="ml-2"><i
							class="fa fa-info-circle" data-toggle="popover"
							data-trigger="hover" data-title="Marketing Campaign"
							data-placement="top"
							data-content="Campaign that run for getting more returning customers."></i></span>
					</div>
					<!-- end title -->
					<!-- begin row -->
					<div class="row align-items-center p-b-1">
						<!-- begin col-4 -->
						<div class="col-4">
							<div
								class="height-100 d-flex align-items-center justify-content-center">
								<img src="..\assets\img\svg\img-2.svg" class="mw-100 mh-100">
							</div>
						</div>
						<!-- end col-4 -->
						<!-- begin col-8 -->
						<div class="col-8">
							<div class="m-b-2 text-truncate">Email Marketing Campaign</div>
							<div class="text-grey m-b-2 f-s-11">Mon 12/6 - Sun 18/6</div>
							<div class="d-flex align-items-center m-b-2">
								<div class="flex-grow-1">
									<div
										class="progress progress-xs rounded-corner bg-white-transparent-1">
										<div class="progress-bar progress-bar-striped bg-indigo"
											data-animation="width" data-value="80%" style="width: 0%"></div>
									</div>
								</div>
								<div class="ml-2 f-s-11 width-30 text-center">
									<span data-animation="number" data-value="80">0</span>%
								</div>
							</div>
							<div class="text-grey f-s-11 m-b-15 text-truncate">57.5% people
								click the email</div>
							<a href="#" class="btn btn-xs btn-indigo f-s-10 pl-2 pr-2">View
								campaign</a>
						</div>
						<!-- end col-8 -->
					</div>
					<!-- end row -->
					<hr class="bg-white-transparent-2 m-t-20 m-b-20">
					<!-- begin row -->
					<div class="row align-items-center">
						<!-- begin col-4 -->
						<div class="col-4">
							<div
								class="height-100 d-flex align-items-center justify-content-center">
								<img src="..\assets\img\svg\img-3.svg" class="mw-100 mh-100">
							</div>
						</div>
						<!-- end col-4 -->
						<!-- begin col-8 -->
						<div class="col-8">
							<div class="m-b-2 text-truncate">Facebook Marketing Campaign</div>
							<div class="text-grey m-b-2 f-s-11">Sat 10/6 - Sun 18/6</div>
							<div class="d-flex align-items-center m-b-2">
								<div class="flex-grow-1">
									<div
										class="progress progress-xs rounded-corner bg-white-transparent-1">
										<div class="progress-bar progress-bar-striped bg-warning"
											data-animation="width" data-value="60%" style="width: 0%"></div>
									</div>
								</div>
								<div class="ml-2 f-s-11 width-30 text-center">
									<span data-animation="number" data-value="60">0</span>%
								</div>
							</div>
							<div class="text-grey f-s-11 m-b-15 text-truncate">+124k visitors
								from facebook</div>
							<a href="#" class="btn btn-xs btn-warning f-s-10 pl-2 pr-2">View
								campaign</a>
						</div>
						<!-- end col-8 -->
					</div>
					<!-- end row -->
				</div>
				<!-- end card-body -->
			</div>
			<!-- end card -->
		</div>
		<!-- end col-4 -->
	</div>


</div>

<script>
	$(document).ready(function() {
		App.init();
// 		Highlight.init();
	});
</script>