<?php
namespace Settings\Entity\Repository;

class CountryRepository extends \Doctrine\ORM\EntityRepository
{

    public function count(array $criteria = null)
    {
//        return parent::count($criteria); // TODO: Change the autogenerated stub
        $query = $this->getEntityManager()->createQueryBuilder();
        $result = $query->select("c.id")->from("Settings\Entity\Country", "c");
        return count($result->getQuery()->getResult());

    }


    public function getItems($offset, $itemCountPerPage){
        $query = $this->getEntityManager()->createQueryBuilder();
        $result = $query->select(array("c.id", "c.name"))->from("Settings\Entity\Country", "c")
            ->setFirstResult($offset)
            ->setMaxResults($itemCountPerPage);;
        return $result->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

}