<?php

?>

<div class="slim-mainpanel">
	<div class="container container-messages">
		<div class="messages-left">
			
			<!--  Advert placement here  -->
		</div>
		<!-- messages-left -->

		<div class="messages-right">
			<div class="message-header">
				<a href="" class="message-back"><i class="fa fa-angle-left"></i></a>
				<div class="media">
					<img src="http://via.placeholder.com/500x500" alt="">
					<div class="media-body">
						<h6>Joyce Chua</h6>
						<p>Last seen: 2 hours ago</p>
					</div>
					<!-- media-body -->
				</div>
				<!-- media -->
				<div class="message-option">
					<div class="d-none d-sm-flex">
						<a href=""><i class="icon ion-ios-telephone-outline"></i></a> <a
							href=""><i class="icon ion-ios-videocam-outline"></i></a> <a
							href=""><i class="icon ion-ios-gear-outline"></i></a> <a href=""><i
							class="icon ion-ios-information-outline"></i></a>
					</div>
					<div class="d-sm-none">
						<a href=""><i class="icon ion-more"></i></a>
					</div>
				</div>
			</div>
			<!-- message-header -->
			<div class="message-body">
				<div class="media-list">
					<div class="media">
						<img src="http://via.placeholder.com/500x500" alt="">
						<div class="media-body">
							<div class="msg">
								<p>Hi, there?</p>
							</div>
							<div class="msg">
								<p>Are you ready for our party tonight?</p>
							</div>
						</div>
						<!-- media-body -->
					</div>
					<!-- media -->
					<div class="media">
						<div class="media-body reverse">
							<div class="msg">
								<p>So this is where you plan to do it?</p>
							</div>
						</div>
						<!-- media-body -->
						<img src="http://via.placeholder.com/500x500"
							class="wd-50 rounded-circle" alt="">
					</div>
					<!-- media -->
					<div class="media">
						<img src="http://via.placeholder.com/500x500" alt="">
						<div class="media-body">
							<div class="msg">
								<p>As good a place as any.</p>
							</div>
						</div>
						<!-- media-body -->
					</div>
					<!-- media -->
					<div class="media">
						<div class="media-body reverse">
							<div class="msg">
								<p>At least have the balls to call this what it is: murder. You
									really believe if you walk back onto that farm alone, no me, no
									Randall...</p>
							</div>
							<div class="msg">
								<p>You really believe they're gonna buy whatever bullshit story
									you cook up?</p>
							</div>
						</div>
						<!-- media-body -->
						<img src="http://via.placeholder.com/500x500"
							class="wd-50 rounded-circle" alt="">
					</div>
					<!-- media -->
					<div class="media">
						<img src="http://via.placeholder.com/500x500" alt="">
						<div class="media-body">
							<div class="msg">
								<p>That's just it, it ain't no story. I saw that prisoner shoot
									you down. I ran after him, I snapped his neck. It ain't gonna
									be easy, but Lori and Carl, they'll get over you. They done it
									before. They just gonna have to.</p>
							</div>
						</div>
						<!-- media-body -->
					</div>
					<!-- media -->
				</div>
				<!-- media-list -->
			</div>
			<!-- message-body -->
			<div class="message-footer">
				<div class="row row-sm">
					<div class="col-9 col-sm-8 col-xl-9">
						<input type="text" class="form-control"
							placeholder="Type something here...">
					</div>
					<!-- col-8 -->
					<div class="col-3 col-sm-4 col-xl-3 tx-right">
						<div class="d-none d-sm-block">
							<a href=""><i class="icon ion-happy-outline"></i></a> <a href=""><i
								class="icon ion-ios-game-controller-b-outline"></i></a> <a
								href=""><i class="icon ion-ios-camera-outline"></i></a> <a
								href=""><i class="icon ion-ios-mic-outline"></i></a>
						</div>
						<div class="d-sm-none">
							<a href=""><i class="icon ion-more"></i></a>
						</div>
					</div>
					<!-- col-4 -->
				</div>
				<!-- row -->
			</div>
			<!-- message-footer -->
		</div>
		<!-- messages-right -->
	</div>
	<!-- container -->
</div>