<?php
use General\Service\GeneralService;
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:v="urn:schemas-microsoft-com:vml"
	xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="format-detection" content="telephone=no" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Order Received (Nike.com #RGE00506500)</title>
<link rel="shortcut icon" href="https://www.nike.com/favicon.ico"
	type="image/x-icon" />
<style>
body, table, td, p, a, li, blockquote {
	-ms-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
}

body {
	height: 100% !important;
	margin: 0 !important;
	padding: 0 !important;
	width: 100% !important;
}

table {
	border-spacing: 0;
	mso-table-lspace: 0pt;
	mso-table-rspace: 0pt;
}

table td {
	border-collapse: collapse;
}

.maindiv, .maintable {
	width: 100% !important;
	width: -o-calc(100%) !important;
	width: -moz-calc(100%) !important;
	width: -webkit-calc(100%) !important;
	max-width: 1000px !important;
	width: calc(100%) !important;
}

.ghostcell {
	display: inline;
}

.ghostdiv {
	font-size: 0px !important;
	font-size: 0;
	display: inline-block !important;
	margin: 0px !important;
	padding: 0px !important;
	border: none !important;
	border-collapse: collapse;
	border-spacing: 0px;
}

.maincontainer {
	font-size: 0px !important;
	margin: 0px !important;
	border: none !important;
}

.innershell {
	font-size: 0px !important;
	padding: 0px !important;
	margin: 0px !important;
	border: none !important;
	border-spacing: 0;
}

.container {
	padding: 0px !important;
	margin: 0px !important;
	border: none !important;
	border-spacing: 0;
}

.contentcontainer {
	font-size: 16px;
}

a[x-apple-data-detectors] {
	color: inherit !important;
	text-decoration: none !important;
	font-size: inherit !important;
	font-family: inherit !important;
	font-weight: inherit !important;
	line-height: inherit !important;
}

.address a {
	color: inherit !important;
	text-decoration: none !important;
}

@media screen and (-webkit-min-device-pixel-ratio: 0) {
	h1 {
		text-transform: uppercase;
	}
	.button {
		text-transform: uppercase;
	}
}

@media only screen and (max-width: 800px) {
	.maintable {
		min-width: 648px !important;
		width: 648px !important;
	}
	.innershell {
		width: 640px !important;
	}
}

@media only screen and (max-width: 580px) {
	.maintable {
		max-width: 400px !important;
		width: 100% !important;
		min-width: 320px !important;
	}
	.maincontainer {
		min-width: 320px !important;
		width: 100% !important;
	}
	.outershell {
		max-width: 400px !important;
		width: 100% !important;
	}
	.innershell {
		width: 100% !important;
	}
	.button {
		width: 87% !important;
	}
	.utiltd {
		width: 100% !important;
	}
	.utiltab {
		max-width: 100% !important;
	}
	.mb-dskt-laydown {
		display: none !important;
		width: 0px !important;
		height: 0px !important;
		overflow: hidden !important;
	}
	.mb-mob-laydown {
		display: inline-block !important;
		width: 100% !important;
		height: auto !important;
	}
}

@media only screen and (max-width: 480px) {
	.outershell {
		max-width: 330px !important;
		width: 100% !important;
	}
	.innershell {
		width: 100% !important;
	}
	.ghostcell {
		display: block !important;
	}
	.ghosttable {
		width: 100% !important;
	}
}

@media only screen and (max-width: 420px) {
	.sidebar {
		width: 0px !important;
		max-width: 0px !important;
	}
	.outershell {
		border: 0 !important;
	}
	.maincontainer {
		padding: 0px !important;
	}
}
</style>
<style type="text/css">
@font-face {
	font-family: "Nike TG";
	font-style: normal;
	font-weight: 700;
	src:
		url(http://assets.commerce.nikecloud.com/ncss/0.16/dotcom/fonts/257c802f-349c-4b4d-aefa-546d5de15ec6.eot);
	src:
		url(http://assets.commerce.nikecloud.com/ncss/0.16/dotcom/fonts/257c802f-349c-4b4d-aefa-546d5de15ec6.eot?#iefix)
		format("embedded-opentype"),
		url(http://assets.commerce.nikecloud.com/ncss/0.16/dotcom/fonts/257c802f-349c-4b4d-aefa-546d5de15ec6.woff)
		format("woff"),
		url(http://assets.commerce.nikecloud.com/ncss/0.16/dotcom/fonts/257c802f-349c-4b4d-aefa-546d5de15ec6.ttf)
		format("truetype"),
		url(http://assets.commerce.nikecloud.com/ncss/0.16/dotcom/fonts/257c802f-349c-4b4d-aefa-546d5de15ec6.svg#257c802f-349c-4b4d-aefa-546d5de15ec6)
		format("svg");
}
</style>
</head>
<center>
	<body align="center"
		style="text-align: center; width: 100%; height: 100%; margin: 0; padding: 0px; -ms-text-size-adjust: 100%;">
		<div align="center"
			style="text-align: center; display: none; font-size: 1px; color: #333333; line-height: 1px; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;">Get
			your order summary, estimated delivery date and
			more.&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
			&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</div>
		<div class="maindiv" align="center" width="100%" height="100%"
			style="text-align: center; font-size: 0px;">
			<img
				src="http://click.official.nike.com/open.aspx?ffcb10-fe9115747263067c7d-fe1f13787262037d731576-fe9815737560077476-ff2a17777163-fe261377776c047a7d1670-fec915767160047a"
				width="1" height="1">
			<table class="maintable" width="100%" align="center" cellspacing="0"
				cellpadding="0" border="0" style="padding: 0px; font-size: 0px;"
				role="presentation">
				<tr>
					<td class="sidebar"
						style="font-size: 0px; line-height: 1px; overflow: hidden !important;">&nbsp;</td>
					<td class="outershell" width="642" valign="top" align="center"
						style="width: 642px; max-width: 642px !important; min-width: 320px !important; border: 1px solid #E5E5E5;">
						<table class="innershell" bgcolor="#FFFFFF" align="center"
							width="100%" valign="top" cellpadding="0" cellspacing="0"
							border="0"
							style="border: none; width: 100%; min-width: 320px !important; max-width: 640px !important; padding: 0px; border-collapse: collapse;"
							role="presentation">
							<tr>
								<td class="container" align="center">
									<!-- Start Email Content -->
									<table align="center" width="100%" cellspacing="0"
										cellpadding="0" border="0" style="width: 100%">
										<tr>
											<td align="center" style="border-bottom: 1px solid #E5E5E5;">

												<!-- colShell -->
												<table width="100%" style="border-spacing: 0px;"
													role="presentation">
													<tr>
														<td bgcolor="#F7F7F7" align="center" style="padding: 0px;">
															<table align="center" width="94%" valign="top"
																cellpadding="0" cellspacing="0" border="0"
																style="margin: 0px auto; max-width: 100%; min-width: 320px; border: none; border-collapse: collapse;"
																role="presentation">
																<tr>
																	<td align="left" valign="middle"
																		style="padding: 20px 20px 20px 20px; font-size: 0px;">
																		<table width="100%" role="presentation">
																			<tr>
																				<td valign="top" align="left"
																					style="color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 26px; padding: 0px;">
																					Delivering to: <?php  echo $fullname ; var_dump(count($cartDetails))?></td>
																			</tr>
																			<tr>
																				<td valign="top" align="left"
																					style="color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px;">
																					<p
																						style="color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px; margin: 0px;">
																						<span class="address"><?php  echo $address ?><br /><?php  //echo $city ?>, <?php // echo $country ?>
																						</span>
																					</p>
																				</td>
																			</tr>

																			<!--[if mso]>
<tr>
<td style="margin:0px; padding:0px 0px 5px 0px; display:inline-block;"></td>
</tr>
<![endif]-->
																		</table>
																	</td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#ffffff" align="center"
															style="border-top: 1px solid #E5E5E5; padding: 0px;">
															<!-- Primary Component -->
															<div
																style="line-height: 0px; padding: 0px; width: 0px; height: 0px; display: none !important; mso-hide: all;">
															</div>
															<div
																style="line-height: 0px; padding: 0px; width: 0px; height: 0px; display: none !important; mso-hide: all;">
															</div>
															<table width="100%" role="presentation">
																<tr>
																	<td
																		style="text-align: center; font-size: 14px; padding: 50px 0px 20px 0px;"
																		align="center">
																		<!-- Container -->
																		<table
																			style="border-spacing: 0px; min-width: 275px; width: 65%; margin: 0px auto;"
																			role="presentation">

																			<!-- Container Cell -->
																			<tr>
																				<td
																					style="padding: 0px 0px 30px 0px; text-align: center;"
																					align="left"><a target="_blank"
																					href="<?php echo GeneralService::COMPANY_URL?>"><img
																						style="border: none; border-width: 0px;"
																						src="<?php echo $logo ?>" width="57" alt="logo" /></a></td>
																			</tr>

																			<!-- Container Cell -->
																			<tr>
																				<td
																					style="padding: 0px 0px 15px 0px; text-align: center;"
																					align="left">
																					<h1
																						style="color: #111111; font-size: 28px; line-height: 34px; font-family: Helvetica, Arial, sans-serif; margin: 0px;">
																						<span
																							style="color: #111111; font-size: 28px; line-height: 34px; font-family: 'Nike TG', Helvetica, Arial, sans-serif !important;">Thanks,
																							<?php  echo $fullname ?>! We're&nbsp;On&nbsp;It.</span>
																					</h1>
																				</td>
																			</tr>

																			<!-- Container Cell -->
																			<tr>
																				<td
																					style="padding: 0px 0px 20px 0px; text-align: center; color: #6D6D6D; line-height: 26px; font-family: Helvetica, Arial, sans-serif;"
																					align="left"><span> Your order's in. We're working
																						to get it packed up and out the door—expect a
																						dispatch confirmation email soon. </span></td>
																			</tr>
																		</table>
																	</td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#ffffff" align="center" style="padding: 0px;">
															<table align="center" width="100%" border="0"
																cellspacing="0" cellpadding="0" style="padding: 0px;">
																<tr>
																	<td bgcolor="#ffffff" align="center"
																		style="border-top: 1px solid #E5E5E5; padding: 0px;">
																		<div
																			style="line-height: 0px; padding: 0px; width: 0px; height: 0px; display: none !important; mso-hide: all;">
																		</div>
																		<table width="94%"
																			style="margin: 0px auto; min-width: 320px;"
																			role="presentation">
																			<tr>
																				<td align="left" style="padding: 40px 0px 40px 0px;">
																					<table class="container" width="100%" align="left"
																						valign="top" border="0" cellpadding="0"
																						cellspacing="0"
																						style="font-size: 14px; color: white; Margin: 0px; padding: 0px; line-height: 17px; border-collapse: collapse;"
																						role="presentation">
																						<tr>
																							<td valign="top" align="left"
																								style="padding: 0px 20px 0px 20px;"><span
																								style="padding: 0px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 22px;">
																									<img
																									src="http://image.official.nike.com/lib/fe9815737560077476/m/3/AlertIcon.png"
																									width="18" height="18"
																									style="padding-top: 3px;" />
																							</span> <span
																								style="color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 26px;">
																									Order Delay Notice: </span> <!--[if (mso)|(mso 10)|(mso 11)|(mso 13)|(mso 16)|(mso 19)]>
<style type="text/css">
span { color: #666666; font-size:14px; font-family: Helvetica,Arial,sans-serif; line-height: 26px; }
</style>
<![endif]--> <span
																								style="color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px;">
																									Due to current measures to protect the safety
																									of our distribution centre employees, please
																									expect delays in processing and delivering your
																									order. </span></td>
																						</tr>
																					</table>
																				</td>
																			</tr>
																		</table>
																	</td>
																</tr>

																<!-- Start EDDheader -->
																<tr>
																	<td bgcolor="#ffffff" align="center"
																		style="padding: 0px;">
																		<table align="center" width="94%" valign="top"
																			cellpadding="0" cellspacing="0" border="0"
																			style="margin: 0px auto; max-width: 100%; min-width: 320px; border: none; border-collapse: collapse;"
																			role="presentation">
																			<tbody>
																				<tr>
																					<td
																						style="padding: 0px; text-align: center; font-size: 14px; padding: 0px 20px 20px 20px;">

																						<!-- Start StyleCell-->
																						<table width="100%" role="presentation">
																							<tr>
																								<td
																									style="padding: 0px 0px; text-align: left; margin: 0px;"
																									align="left"><span
																									style="font-size: 14px; font-family: Helvetica, Arial, sans-serif; color: #017F07; line-height: 24px;">Estimated
																										Delivery Date <?php echo $this->dateformat($estimatedDeliveryDate, IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE)?></span></td>
																							</tr>
																						</table> <!-- End StyleCell -->
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>

																<!-- End EddHeader -->
																
																<?php  echo $basket;?>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#ffffff" align="center"
															style="border-top: 1px solid #E5E5E5; padding: 0px;">
															<table width="94%"
																style="margin: 0px auto; min-width: 320px;"
																role="presentation">
																<tr>
																	<td align="left" style="padding: 20px 0px 20px 0px;">
																		<!--[if mso]>
<table class="ghosttable" align="left" border="0" cellspacing="0" cellpadding="0" width="100%" role="presentation">
<tr>
<td class="ghostcell" align="left" valign="top" width="213" style="width: 233px; display: inline-block;">
<![endif]-->
																		<div class="ghostdiv"
																			style="max-width: 213px !important; border: none; display: inline-table; padding: 0px !important; font-size: 0px; vertical-align: top;">
																			<table class="container" width="233" align="left"
																				valign="top" border="0" cellpadding="0"
																				cellspacing="0"
																				style="max-width: 213px !important; min-width: 213px !important; font-size: 14px; color: white; Margin: 0px; padding: 0px; line-height: 17px; border-collapse: collapse;"
																				role="presentation">
																				<tr>
																					<td valign="top" align="left"
																						style="padding: 20px 0px 0px 20px; color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 26px;">
																						Order Number</td>
																				</tr>
																				<tr>
																					<td valign="top" align="left"
																						style="padding: 0px 0px 0px 20px; color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px;">
																						<?php  echo $orderId ?></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]>
</td><td class="ghostcell" align="left" valign="top" width="367" style="width: 367px; display: inline-block;">
<![endif]-->
																		<div class="ghostdiv"
																			style="width: 100%; max-width: 363px !important; border: none; display: inline-table; padding: 0px !important; font-size: 0px; vertical-align: top;">
																			<table class="container" width="100%" align="left"
																				valign="top" border="0" cellpadding="0"
																				cellspacing="0"
																				style="max-width: 363px; min-width: 320px !important; font-size: 14px; color: white; Margin: 0px; padding: 0px; line-height: 17px; border-collapse: collapse;"
																				role="presentation">
																				<tr>
																					<td valign="top" width="150" align="left"
																						style="width: 150px; padding: 20px 0px 0px 20px; color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 26px;">
																						Order Date</td>
																					<td style="font-size: 0px; max-width: 40px;">&nbsp;</td>
																					<td valign="top" width="150" align="left"
																						style="width: 150px; padding: 20px 0px 0px 20px; color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 26px;">
																						Delivery Method</td>
																				</tr>
																				<tr>
																					<td valign="top" width="150" align="left"
																						style="padding: 0px 0px 20px 20px; color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px;">
																						<?php  echo $this->dateformat($orderDate)?></td>
																					<td style="font-size: 0px; max-width: 40px;">&nbsp;</td>
																					<td valign="top" width="150" align="left"
																						style="padding: 0px 0px 20px 20px; color: #666666; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 26px;">
																						<?php  echo $deliveryMethod?></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]>
</td></tr></table>
<![endif]-->
																		<div class="ghostdiv"
																			style="width: 100%; max-width: 100% !important; border: none; display: inline-table; padding: 0px !important; font-size: 0px; vertical-align: top;">
																			<table class="container" width="100%" align="center"
																				valign="top" border="0" cellpadding="0"
																				cellspacing="0"
																				style="max-width: 100%; min-width: 320px !important; font-size: 14px; color: white; Margin: 0px; padding: 0px; line-height: 17px; border-collapse: collapse;"
																				role="presentation">
																				<tr>
																					<td align="center" style="padding: 20px 0px;">
																						<div
																							style="line-height: 0px; padding: 0px; width: 0px; height: 0px; display: none !important; mso-hide: all;">
																						</div>
																						<table class="button" width="225" align="center"
																							style="margin: 0px auto; height: 40px; width: 225px; border: 1px solid #8D8D8D; border-radius: 2px; display: inline-table;"
																							role="presentation">

																						</table>
																					</td>
																				</tr>
																			</table>
																		</div>
																	</td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#ffffff" align="center"
															style="border-top: 1px solid #E5E5E5; padding: 0px;">
															<table align="center" width="94%" valign="top"
																cellpadding="0" cellspacing="0" border="0"
																style="margin: 0px auto; max-width: 100%; min-width: 320px; border: none; border-collapse: collapse;"
																role="presentation">
																<tr>
																	<td align="left" valign="middle"
																		style="padding: 00px 20px 00px 20px; font-size: 0px;">
																		<table width="100%" role="presentation">
																			<tr>
																				<td align="center"
																					style="color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px; padding: 40px 0px 40px 0px;">
																					<table width="100%" align="center" border="0"
																						cellspacing="0" cellpadding="0"
																						style="padding: 0px; Margin: 0px; border-collapse: collapse;"
																						role="presentation">
																						<tr>
																							<td width="60%" align="left"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;">Payment</td>
																							<td width="40%" align="right"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;"><?php  echo $paymentType ?></td>
																						</tr>
																						<tr>
																							<td width="60%" align="left"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;">Subtotal</td>
																							<td width="40%" align="right"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;"><?php  echo $this->myCurrencyHelper($orderTotal)?></td>
																						</tr>
																						<tr>
																							<td width="60%" align="left"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;">Shipping
																								& Handling</td>
																							<td width="40%" align="right"
																								style="padding: 10px 0px; color: #6D6D6D; font-family: Helvetica, Arial, sans-serif; font-size: 14px; line-height: 24px;"><?php  echo $this->myCurrencyHelper($shipping)?></td>
																						</tr>
																						<tr>
																							<td width="60%" align="left"
																								style="padding: 10px 0px 0px 0px; color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 18px; line-height: 30px;">Total</td>
																							<td width="40%" align="right"
																								style="padding: 10px 0px 0px 0px; color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 18px; line-height: 30px;"><?php  echo $this->myCurrencyHelper($total)?></td>
																						</tr>
																					</table>
																				</td>
																			</tr>
																		</table>
																	</td>
																</tr>
															</table>
														</td>
													</tr>
												</table>
											</td>
										</tr>
										<tr>
											<td align="center"></td>
										</tr>
										<tr>
											<td align="center"></td>
										</tr>
										<tr>
											<td align="center">
												<!--Start Get Help-->
												<table align="center" border="0" cellspacing="0"
													cellpadding="0" width="100%"
													style="margin: 0px; border-collapse: collapse; padding: 0px; background-color: #F7F7F7;"
													role="presentation">
													<tr>
														<td style="font-size: 0px">
															<table align="center" border="0" cellspacing="0"
																cellpadding="0" width="94%"
																style="margin: 0px auto; min-width: 320px; border-collapse: collapse; padding: 0px;"
																role="presentation">
																<tr>
																	<td align="left"
																		style="padding: 40px 0px 0px 20px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 28px;">
																		Get Help</td>
																</tr>
																<tr>
																	<td align="left" valign="top"
																		style="font-size: 0px; padding: 0px 0px 40px 0px; vertical-align: top;">

																		<!--[if mso]>
<table class="ghosttable" align="left" border="0" cellspacing="0" cellpadding="0" width="100%" role="presentation">
<tr><![endif]--> <!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 120px; padding: 25px 20px 0px 20px; font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px;"><a
																						href="/gb/help/a/change-cancel-order-eu"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;">Cancel
																							Order</a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 120px; padding: 25px 20px 0px 20px; font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px;"><a
																						href="https://www.nike.com/gb/help/a/returns-policy-eu?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242982&et_jb=164407&et_mid=1304393"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;">Returns
																							Policy</a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 120px; padding: 25px 20px 0px 20px; font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px;"><a
																						href="https://www.nike.com/gb/help/#contact?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242983&et_jb=164407&et_mid=1304393"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;">Contact
																							Options</a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]></tr><tr><![endif]-->

																		<!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 120px; padding: 25px 20px 0px 20px; font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px;"><a
																						href="https://www.nike.com/gb/en/orders/gift-card-lookup?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242984&et_jb=164407&et_mid=1304393"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;">Gift
																							Card Balance</a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 160px; font-size: 0px; line-height: 1px;"><a
																						href="https://www.nike.com/gb/en/orders/gift-card-lookup?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242984&et_jb=164407&et_mid=1304393"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;"></a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]><td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;"><![endif]-->
																		<div
																			style="display: inline-block; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td
																						style="width: 100%; min-width: 120px; padding: 25px 20px 0px 20px; font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px;"><a
																						href="https://www.nike.com/gb/en/orders/gift-card-lookup?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242984&et_jb=164407&et_mid=1304393"
																						target="_blank"
																						style="font-family: Helvetica, Arial, sans-serif; color: #111111; font-size: 12px; line-height: 20px; text-decoration: none;"></a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]></td><![endif]--> <!--[if mso]></tr></table><![endif]-->
																	</td>
																</tr>
																<tr>
																	<td align="left" valign="top"
																		style="padding: 40px 0px 25px 0px; border-top: 1px solid #E5E5E5; font-size: 0px;">

																		<!--[if mso]>
<table class="ghosttable" align="left" border="0" cellspacing="0" cellpadding="0" width="400" style="width:400px;" role="presentation">
<tr>
<![endif]--> <!--[if mso]>
<td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;">
<![endif]-->
																		<div
																			style="display: inline-table; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%"
																				style="min-width: 160px; margin: 0px auto; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td align="left" valign="top" width="20"
																						height="23"
																						style="min-width: 20px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 22px; padding: 0px 0px 0px 20px;"><img
																						width="14" height="23"
																						src="http://image.official.nike.com/lib/fe9815737560077476/m/3/phone-icon2x.png" /></td>
																					<td align="left" valign="top" width="140"
																						height="23"
																						style="min-width: 140px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 22px; padding: 0px 20px 0px 0px;"><a
																						href="Tel:+44%20(0)%202076604453"
																						style="text-decoration: none; color: #000000; white-space: nowrap;"
																						target="_self" nowrap="nowrap">+44 (0) 2076604453</a></td>
																				</tr>
																			</table>
																		</div> <!--[if mso]>
</td>
<![endif]--> <!--[if mso]>
<td class="ghostcell" align="left" valign="top" width="200" style="width: 200px; display: inline-block;">
<![endif]-->
																		<div
																			style="display: inline-table; max-width: 33.33333%; min-width: 160px; width: 100%; vertical-align: top;">
																			<table border="0" cellspacing="0" cellpadding="0"
																				width="100%" valign="top"
																				style="min-width: 160px; margin: 0px; border-collapse: collapse; padding: 0px;"
																				role="presentation">
																				<tr>
																					<td valign="top"
																						style="color: #111111; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 22px; padding: 0px 20px; text-decoration: none;">
																						<a
																						href="https://www.nike.com/gb/help/#contact?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242986&et_jb=164407&et_mid=1304393"
																						style="text-decoration: underline; color: #000000; white-space: nowrap; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 22px;"
																						target="_blank" nowrap="nowrap">Hours of Operation</a>
																					</td>
																				</tr>
																			</table>
																		</div> <!--[if mso]>
</td>
<![endif]--> <!--[if mso]>
</tr>
</table><![endif]-->
																	</td>
																</tr>
															</table>
														</td>
													</tr>
												</table> <!--End Get Help-->
											</td>
										</tr>
										<tr>
											<td align="center">
												<!-- Start Navigation -->
												<table align="center" border="0" cellspacing="0"
													cellpadding="0" width="100%"
													style="margin: 0px; border-collapse: collapse; padding: 0px;"
													role="presentation">
													<tr>
														<td align="center"
															style="padding: 45px 0px 28px 0px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 24px; line-height: 28px; text-align: center; border-top: 1px solid #E5E5E5;">
															<H1
																style="Margin: 0px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 24px; line-height: 28px;">
																<a
																	href="https://www.nike.com/gb/?cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_jb=164407&et_li=3747_HTML&et_mid=1304393&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_u=62242987"
																	target="_blank"
																	style="Margin: 0px; color: #000000; font-family: Helvetica, Arial, sans-serif; font-size: 24px; line-height: 28px; text-decoration: none;">
																	<span
																	style="color: #000000; font-family: 'Nike TG', Helvetica, Arial, sans-serif !important; font-size: 24px; line-height: 28px;"></span>
																</a>
															</H1>
														</td>
													</tr>
													
												</table> <!-- End Navigation -->
											</td>
										</tr>
										<tr>
											<td align="center">
												<!-- Start Footer -->
												<table align="center" border="0" cellspacing="0"
													cellpadding="0" width="100%"
													style="margin: 0px; border-collapse: collapse; padding: 0px;"
													role="presentation">
													<tr>
														<td align="center"
															style="font-size: 0px; padding: 20px 0px 40px 0px;">
															<table align="center" border="0" cellspacing="0"
																cellpadding="0"
																style="margin: 0px auto; border-collapse: collapse; padding: 0px;"
																role="presentation">
																<tr>
																	<td align="center"
																		style="min-width: 70px; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px; padding: 0px;">
																		<a href="#" target="_blank"
																		style="white-space: nowrap; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px; text-decoration: none;">Web
																			Version</a>
																	</td>
																	<td
																		style="width: 17px; min-width: 17px; font-size: 0px;">&nbsp;</td>
																	<td align="center"
																		style="min-width: 70px; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px; padding: 0px;">
																		<a
																		href="https://agreementservice.svs.nike.com/gb/en_gb/rest/agreement?agreementType=privacyPolicy&uxId=com.nike.unite&country=gb&language=en&requestType=redirect&cp=emeans_em_autoT_XBrand_Noncategory_AAAABBCC_C1715_OrderConf_gb+OrderConf+NMC_CNT+gb_en_MF_V1_z&et_cid=1477218&et_rid=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_sid=C1715_gb+OrderConf+NMC&et_li=3747_HTML&et_e=f0aba4e07eb282bc1d57c506a9cc960c337c65346392d04eaa39f32cfa785dc4&et_u=62242994&et_jb=164407&et_mid=1304393"
																		target="_blank"
																		style="white-space: nowrap; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px; text-decoration: none;">Privacy
																			Policy</a>
																	</td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td align="center"
															style="font-size: 0px; padding: 0px 30px;">
															<p
																style="margin: 0px auto; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px; padding: 0px;">
																Please <a
																	href=""
																	target="_blank"
																	style="white-space: nowrap; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 26px;">contact
																	us</a> if you have any questions. (If you reply to this
																email, we won't be able to see it.)
															</p>
														</td>
													</tr>
													<tr>
														<td align="center"
															style="font-size: 0px; padding: 43px 20px 0px 20px;">
															<p
																style="margin: 0px auto; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 11px; line-height: 22px; padding: 0px;">©
																2021 <?php  echo GeneralService::APP_COMPANY_NAME?>, Inc. All Rights Reserved.</p>
														</td>
													</tr>
													<tr>
														<td align="center"
															style="font-size: 0px; padding: 0px 20px 20px 20px;">
															<p
																style="margin: 0px auto; color: #AAAAAA; font-family: Helvetica, Arial, sans-serif; font-size: 11px; line-height: 22px; padding: 0px;">
																<span class="address" style="text-decoration: none;"><?php  echo GeneralService::APP_COMPANY_NAME?> <?php  echo GeneralService::COMPANY_ADDRESS?></span>
															</p>
														</td>
													</tr>
												</table> <!-- End Footer -->
											</td>
										</tr>
									</table> <!-- End Email Content -->
								</td>
							</tr>
						</table>
					</td>
					<td class="sidebar"
						style="font-size: 0px; line-height: 1px; overflow: hidden !important;">&nbsp;</td>
				</tr>
			</table>
		</div>
	</body>
</center>
</html>