<?php
use General\Service\GeneralService;
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">









</head>

<body>

	<div style="text-align: left">
		<table cellpadding="10" cellspacing="0"
			style="width: 100%; height: 100%; background-color: rgb(255, 255, 255)">
			<tbody>
				<tr>
					<td valign="top">
						<table align="center" cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td>
										<table cellpadding="0" cellspacing="0" style="width: 586px">
											<tbody>
												<tr>
													<td
														style="text-align: left; margin: 0px; padding: 10px 0px; border: none; white-space: normal; line-height: normal">
														<div>
															<div>
																<div
																	style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 11px; font-family: arial; color: rgb(26, 36, 46); text-align: center; background: none">
																	<div
																		style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 11px; font-family: arial; color: rgb(26, 36, 46); text-align: center; background: none">
																		<div>
																			<p style="font-size: 0px">A Message from the CEO |</p>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</td>
												</tr>
												<tr>
													<td
														style="text-align: left; margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; height: 30px; background-color: rgb(255, 255, 255)">
														<div>
															<div style="min-height: 15px; line-height: 15px"> </div>
														</div>
														<div>
															<table width="100%" cellspacing="0" cellpadding="0"
																style="max-width: 586px; margin: 0px auto">
																<tbody>
																	<tr>
																		<td style="text-align: center"><a
																			href="<?php echo GeneralService::COMPANY_URL?>"
																			target="_blank"> <img src="<?php echo $logo ?>"
																				alt="<?php echo GeneralService::APP_COMPANY_NAME ?>"
																				style="min-height: auto; max-width: 265px; margin: 30px 0px">
																		</a></td>
																	</tr>
																	<tr>
																		<td style="text-align: left; max-width: 550px">
																			<p
																				style="text-align: left; margin: 0px auto; font-family: &amp; amp; amp; #39; Century Gothic&amp;amp; amp; #39; , CenturyGothic ,AppleGothic,sans-serif; font-size: 18px; line-height: 32px; color: rgb(0, 0, 0)">
																				<br>Hi <?php  echo $name ?>
                                                    <br> <br>I know
																				you&#39; might find it a little strenuous completing
																				you payment this way <br> <br>We just want to inform
																				you we have received your notification and will
																				process your cart. <br> <br>Continue your
																				entrepreneural journey, we are proud of you! <br>
																			</p>
																		</td>
																	</tr>
																</tbody>
															</table>
														</div>
														<div>
															<div
																style="min-height: 15px; line-height: 15px; margin-top: 15px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(119, 119, 119)"> </div>
														</div>
														<div>
															<div
																style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 12px; font-family: arial; color: rgb(0, 0, 0); background: none">
																<div
																	style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 12px; font-family: arial; color: rgb(0, 0, 0); background: none">

																</div>
															</div>
														</div>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<table bgcolor="#FFFFFF" cellpadding="20" cellspacing="0"
		style="width: 587px; text-align: center; background-color: rgb(255, 255, 255)"
		align="center">
		<tbody>
			<tr>
				<td
					style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; text-align: center; background-color: rgb(255, 255, 255)"
					valign="top">
					<div>
						<div style="min-height: 15px; line-height: 15px"> </div>
					</div>
					<div>
						<div style="min-height: 15px; line-height: 15px"> </div>
					</div>
				</td>
			</tr>
			<tr>
				<td
					style="margin: 0px; padding: 20px; border: none; white-space: normal; line-height: normal; text-align: center; background-color: rgb(255, 255, 255)"
					valign="top">
					<div>
						<div
							style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 10px; font-family: verdana; color: rgb(0, 0, 0); text-align: center; background: none"><?php echo GeneralService::APP_COMPANY_NAME ?> :: <?php echo GeneralService::COMPANY_ADDRESS ?></div>
					</div>
					<div>
						<div
							style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 10px; font-family: verdana; color: rgb(0, 0, 0); background: none">
							<div
								style="margin: 0px; padding: 0px; border: none; white-space: normal; line-height: normal; overflow: visible; font-size: 10px; font-family: verdana; color: rgb(0, 0, 0); text-align: center; background: none">

							</div>
						</div>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
	<img alt="<?php echo GeneralService::APP_COMPANY_NAME?>"
		src="<?php echo $logo ?>">
	</div>
	</div>
	<br>
	</div>
	</div>
	</div>
	</div>
	<br>
	</div>





</body>
</html>
