<?php
echo $this->headtitle("Order Returns");
?>
<script>
		$(document).ready(function() {
			App.init();

			TableManageResponsive.init();
		});
	</script>
	
	<script src="/admin/assets/plugins/DataTables/media/js/jquery.dataTables.js"></script>
	<script src="/admin/assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>
	<script src="/admin/assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
	<script src="/admin/assets/js/demo/table-manage-responsive.demo.min.js"></script>