
<div class="form-group row m-b-15">
						<?php echo $this->formlabel($fieldset->get("title"))?>
						<div class="col-md-8 col-sm-8">
<!-- 							<input class="form-control" ref="programmesTopic" -->
<!-- 								v-on:change="handleProgrammesTopic()" type="text" -->
<!-- 								id="programmesTopic" name="programmesTopic" -->
<!-- 								placeholder="required" data-parsley-required="true" /> -->

<?php  echo $this->formtext($fieldset->get("title"))?>
						</div>
					</div>

