<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Shop\Module'                        => __DIR__ . '/Module.php',
    'Shop\Controller\ShopController' => __DIR__ . '/src/Shop/Controller/ShopController.php',
    'ShopTest\Framework\TestCase'        => __DIR__ . '/tests/Shop/Framework/TestCase.php',
    'ShopTest\SampleTest'                => __DIR__ . '/tests/Shop/SampleTest.php',
);
