<?php
use General\Service\GeneralService;
?>

<div class="page-error-wrapper">
	<div>
		<h1 class="error-title"><?php echo $this->translate('A 404 error occurred') ?></h1>
		<h5 class="tx-sm-24 tx-normal">Oopps. The page you were looking for
			doesn't exist.</h5>
		<p class="mg-b-50">You may have mistyped the address or the page may
			have moved.</p>
		<p class="mg-b-50">
			<a href="<?php  echo $this->url("home")?>" class="btn btn-error">Back to Home</a>
		</p>
		<p class="error-footer">&copy; Copyright 2018. All Rights Reserved.
			<?php  echo GeneralService::APP_COMPANY_NAME?></p>
	</div>
</div>
<h2><?php //echo $this->message ?></h2>



<?php if (isset($this->controller) && $this->controller): ?>

<dl>
	<dt><?php echo $this->translate('Controller') ?>:</dt>
	<dd><?php echo $this->escapeHtml($this->controller) ?>
<?php
    if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller) {
        echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
    }
    ?>
</dd>
</dl>

<?php endif ?>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<hr />
<h2><?php echo $this->translate('Additional information') ?>:</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
	<dt><?php echo $this->translate('File') ?>:</dt>
	<dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
	</dd>
	<dt><?php echo $this->translate('Message') ?>:</dt>
	<dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
	</dd>
	<dt><?php echo $this->translate('Stack trace') ?>:</dt>
	<dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
	</dd>
</dl>
<?php
        $e = $this->exception->getPrevious();
        if ($e) :
            ?>
<hr />
<h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
		<h3><?php echo get_class($e); ?></h3>
		<dl>
			<dt><?php echo $this->translate('File') ?>:</dt>
			<dd>
				<pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
			</dd>
			<dt><?php echo $this->translate('Message') ?>:</dt>
			<dd>
				<pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
			</dd>
			<dt><?php echo $this->translate('Stack trace') ?>:</dt>
			<dd>
				<pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
			</dd>
		</dl>
	</li>
    <?php
                $e = $e->getPrevious();
            endwhile
            ;
            ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?php //echo $this->translate('No Exception available') ?></h3>

<?php endif ?>

<?php endif ?>
