<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Jobber\Module'                        => __DIR__ . '/Module.php',
    'Jobber\Controller\JobberController' => __DIR__ . '/src/Jobber/Controller/JobberController.php',
    'JobberTest\Framework\TestCase'        => __DIR__ . '/tests/Jobber/Framework/TestCase.php',
    'JobberTest\SampleTest'                => __DIR__ . '/tests/Jobber/SampleTest.php',
);
