<?php
?>
<div class="form-group row m-b-15">
									
									<?php  echo $this->formlabel($fieldset->get("category"), " <span class='text-danger'> *</span>", "prepend")?>
									<div class="col-md-8 col-sm-8">
		<!-- 										<input class="form-control" type="text" id="fullname" name="fullname" placeholder="Required" data-parsley-required="true" /> -->
									<?php  echo $this->formtext($fieldset->get("category"));?>
									</div>
</div>

<div class="form-group row m-b-15">
									
									<?php  echo $this->formlabel($fieldset->get("image"), " <span class='text-danger'> *</span>", "prepend")?>
<div class="col-md-8 col-sm-8">
	<!-- 										<input class="form-control" type="text" id="fullname" name="fullname" placeholder="Required" data-parsley-required="true" /> -->
									<?php  echo $this->formfile($fieldset->get("image"));?>
									</div>
</div>