<?php
?>
<div class="row">
	<div class="panel panel-inverse" data-sortable-id="table-basic-5">
		<!-- begin panel-heading -->
		<div class="panel-heading">
			
			<h4 class="panel-title">Table Striped</h4>
		</div>
		<!-- end panel-heading -->
		<!-- begin panel-body -->
		<div class="panel-body">
			<!-- begin table-responsive -->
			<div class="table-responsive">
				<table class="table table-striped m-b-0">
					
					<tbody>
					productName
					<tr>
							
							<th>Product Name</th>
							<td>{{productFeatureType}}</td>
						</tr>
						
						<tr>
							
							<th>Product Name</th>
							<td>{{productFeatureType}}</td>
						</tr>
						<tr>
							<td>2</td>
							<td>Edmund Wong</td>
							<td>edmund@yahoo.com</td>
						</tr>
						<tr>
							<td>3</td>
							<td>Harvinder Singh</td>
							<td>harvinder@gmail.com</td>
						</tr>
					</tbody>
				</table>
			</div>
			<!-- end table-responsive -->
		</div>
		<!-- end panel-body -->

	</div>

</div>