<?php
echo $this->headtitle("Customer Wallets");
?>

<div id="content" >
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <!--				<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>-->
        <!--				<li class="breadcrumb-item"><a href="javascript:;">Tables</a></li>-->
        <!--				<li class="breadcrumb-item"><a href="javascript:;">Managed Tables</a></li>-->
        <!--				<li class="breadcrumb-item active">Responsive</li>-->
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">All Customer Wallet <small> A list of all customer Wallet</small></h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-2 -->
        <div class="col-lg-2">
            <h5>
                Key features include:
            </h5>
            <ul class="p-l-25 m-b-15">
                <li>Provides </li>
                <li>Link to view a specific users wallet</li>
                <li>Share information about the count state of a status</li>
                <li>indicate promo status of any product</li>

            </ul>

        </div>
        <!-- end col-2 -->
        <!-- begin col-10 -->
        <div class="col-lg-10">
            <!-- begin panel -->
            <div class="panel panel-inverse">
                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
<!--                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>-->
                    </div>
                    <h4 class="panel-title">Product List</h4>
                </div>
                <!-- end panel-heading -->
                <!-- begin alert -->
                <div class="alert alert-secondary fade show">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <!--                            In the modern world of responsive web design tables can often cause a particular problem for designers due to their row based layout. Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.-->
                </div>
                <!-- end alert -->
                <!-- begin panel-body -->
                <div class="panel-body">
                    <table id="data-table-responsive" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="1%"></th>
                            <th width="1%" data-orderable="false"></th>
                            <th class="text-nowrap">Product Name</th>
                            <th class="text-nowrap">Product Prices</th>
                            <th class="text-nowrap">Date Uploaded</th>
                            <th class="text-nowrap">Quantity</th>
                            <th class="text-nowrap">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if(count($wallets) > 0):?>
                            <?php  foreach ($wallets as $wallet):?>
                                <tr class="odd gradeX">
                                    <td width="1%" class="f-s-600">1</td>
                                    <td width="1%" class="with-img"><img src="<?php  $image ?>" class="img-rounded height-30" /></td>
                                    <td><?php echo $wallet["walletUid"]; ?></td>
                                    <td>Internet Explorer 4.0</td>
                                    <td>Win 95+</td>
                                    <td>4</td>
                                    <td><a class="btn btn-dark" href="<?php echo $this->url("bbminwallet/default", array("action"=>"user-wallet"))?>">View Wallet</a></td>
                                </tr>
                            <?php  endforeach; ?>
                        <?php else:?>
                            <h5>No product Uploaded</h5>
                        <?php endif; ?>


                        </tbody>
                    </table>
                </div>
                <!-- end panel-body -->
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-10 -->
    </div>
    <!-- end row -->
</div>




<script src="/admin/assets/plugins/DataTables/media/js/jquery.dataTables.js"></script>
<script src="/admin/assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>
<script src="/admin/assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script src="/admin/assets/js/demo/table-manage-responsive.demo.min.js"></script>
<!-- ================== END PAGE LEVEL JS ================== -->


