
<div class="col-lg-12 mg-t-20 mg-lg-t-0">
	<div class="section-wrapper">
		<label class="section-title">Notify Your Payment</label>

		<div class="form-layout form-layout-5">
		<?php
$form->prepare();
echo $this->form()->openTag($form);
$fieldset = $form->get("notifyPaymentFieldset");  
?>

<div class="row">
				
					<?php  echo $this->formlabel($fieldset->get("nameOfPayee"), '<span class="tx-danger">*</span>', "prepend")?>
					
				<div class="col-sm-8 mg-t-10 mg-sm-t-0">
					<?php  echo $this->forminput($fieldset->get("nameOfPayee"))?>
	</div>
	<div style="font-size: 9px; color: red;">
              <?php
              echo $this->formElementErrors($fieldset->get("nameOfPayee"));
            ?>
              </div>
			</div>
			<!-- row -->
			<div class="row mg-t-20">
				<?php  echo $this->formlabel($fieldset->get("datePaid"), '<span class="tx-danger">*</span>', "prepend")?>

	<div class="col-sm-8 mg-t-10 mg-sm-t-0">
					<?php  echo $this->forminput($fieldset->get("datePaid"))?>
				</div>
				<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($fieldset->get("datePaid"));
            ?>
              </div>
			</div>
			<div class="row mg-t-20">
				<?php  echo $this->formlabel($fieldset->get("amountPaid"), '<span class="tx-danger">*</span>', "prepend")?>

	<div class="col-sm-8 mg-t-10 mg-sm-t-0">
		<?php echo $this->forminput($fieldset->get("amountPaid"));?>
	</div>
	<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($fieldset->get("amountPaid"));
            ?>
              </div>
			</div>

			<div class="row mg-t-20">
				<?php  echo $this->formlabel($fieldset->get("paymentDetails"))?>

	<div class="col-sm-8 mg-t-10 mg-sm-t-0">
		<?php echo $this->forminput($fieldset->get("paymentDetails"));?>
	</div>

				<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($fieldset->get("paymentDetails"));
            ?>
              </div>
			</div>

			<div class="row mg-t-30">
				<div class="col-sm-8 mg-l-auto">
					<div class="form-layout-footer">
		
			<?php 
			echo $this->formhidden($form->get("cartOrder"));
			echo $this->formsubmit($form->get("submit"))?>
			
		</div>
					<!-- form-layout-footer -->
				</div>
				<!-- col-8 -->
			</div>
<?php
echo $this->form()->closeTag();

?>
<div style="text-align: center;">
				<i id="profileaction" class="fa  fa-lg" style="display: none;"><img
					alt="" src="<?php  echo $this->basepath("/pro.gif")?>" height=27></i>
			</div>
		</div>

		<!-- form-layout -->
	</div>

	<!-- section-wrapper -->
</div>
<!-- col-6 -->