<?php
if(count($orders) > 0):
?>

<table class="table">
							<thead>
								<tr>
									<th>Date</th>
									<th class="hidden-sm">Product</th>
									<th></th>
									<th>Amount</th>
									<th>User</th>
								</tr>
							</thead>
							<tbody>
							<?php foreach ($order as $order):?>
								<tr>
									<td><?php echo $this->dateformat($order->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us");?></td>
									<td class="hidden-sm"><a href="javascript:;"> <img
											src="<?php echo $order->getCart()->get ?>" alt="" />
									</a></td>
									<td class="text-nowrap">
										<h6>
											<a href="javascript:;"><?php  echo $order->getOrderUid()?>
											</a>
										</h6>
									</td>
									<td><?php  echo $this->myCurrencyHelper($order->getTotal())?></td>
									<td class="text-nowrap">Derick Wong</td>
								</tr>
								<?php endforeach;?>
								
							</tbody>
						</table>
						<a href="" class="btn btn-block btn-success"> View All</a>
						<?php else :?>
						<p>No Order Availaible</p>
						
						<?php endif;?>
						