<?php

?>

<div v-if="cartOrders.length" class="row row-xs mg-t-10">
          <div class="col-lg-6">
            <div class="card card-table">
              <div class="card-header">
                <h6 class="slim-card-title">Outstanding Orders</h6>
              </div><!-- card-header -->
              <div class="table-responsive">
                <table class="table mg-b-0 tx-13">
                  <thead>
                    <tr class="tx-10">
                      <th class="wd-10p pd-y-5">&nbsp;</th>
                      <th class="pd-y-5">Products</th>
                      <th class="pd-y-5">Payment Type</th>
                      <th class="pd-y-5">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="item in cartOrders" :key="item.id">
                      <td class="pd-l-20">
                        <img :src="item.cart.cartItems[0].product.image[0].thumbnail" class="wd-36 rounded-circle" alt="Image">
                      </td>
                      <td>
                        <a :href="createoderLink(item.orderUid)" class="tx-inverse tx-14 tx-medium d-block">{{item.cart.cartItems.length}} Product(s)</a>
                        <span class="tx-11 d-block">ORDER ID: {{item.orderUid.toUpperCase()}}</span>
                      </td>
                      <td class="tx-12">
                        <span class="square-8 bg-success mg-r-5 rounded-circle"></span> {{item.paymentMethod.paymentMethod}}
                      </td>
                      <td>{{item.orderStatus.status.toUpperCase()}}</td>
                    </tr>
                    
                  </tbody>
                </table>
              </div><!-- table-responsive -->
              <div class="card-footer tx-12 pd-y-15 bg-transparent">
<!--                 <a href=""><i class="fa fa-angle-down mg-r-5"></i>View All Order History</a> -->
              </div><!-- card-footer -->
            </div><!-- card -->
          </div><!-- col-6 -->
          <div class="col-lg-6 mg-t-10 mg-lg-t-0">
            <div class="card card-table">
              
            </div><!-- card -->
          </div><!-- col-6 -->
        </div><!-- row -->