<div class="row row-sm mg-t-20">
			<div class="col-lg-4">
				<div class="card card-sales">
					<h6 class="slim-card-title tx-primary">Sales Report</h6>
					<div class="row">
						<div class="col">
							<label class="tx-12">Today</label>
							<p>1,898</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Week</label>
							<p>32,112</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Month</label>
							<p>72,067</p>
						</div>
						<!-- col -->
					</div>
					<!-- row -->

					<div class="progress mg-b-5">
						<div class="progress-bar bg-primary wd-50p" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
					</div>
					<p class="tx-12 mg-b-0">Maecenas tempus, tellus eget conditum rhon.</p>
				</div>
				<!-- card -->
			</div>
			<!-- col-4 -->
			<div class="col-lg-4 mg-t-20 mg-lg-t-0">
				<div class="card card-sales">
					<h6 class="slim-card-title tx-success">Sales Report</h6>
					<div class="row">
						<div class="col">
							<label class="tx-12">Today</label>
							<p>1,263</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Week</label>
							<p>28,767</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Month</label>
							<p>68,324</p>
						</div>
						<!-- col -->
					</div>
					<!-- row -->

					<div class="progress mg-b-5">
						<div class="progress-bar bg-success wd-75p" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
					</div>
					<p class="tx-12 mg-b-0">Maecenas tempus, tellus eget conditum rhon.</p>
				</div>
				<!-- card -->
			</div>
			<!-- col-4 -->
			<div class="col-lg-4 mg-t-20 mg-lg-t-0">
				<div class="card card-sales">
					<h6 class="slim-card-title tx-danger">Sales Report</h6>
					<div class="row">
						<div class="col">
							<label class="tx-12">Today</label>
							<p>1,263</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Week</label>
							<p>28,767</p>
						</div>
						<!-- col -->
						<div class="col">
							<label class="tx-12">This Month</label>
							<p>68,324</p>
						</div>
						<!-- col -->
					</div>
					<!-- row -->

					<div class="progress mg-b-5"> -->
						<div class="progress-bar bg-danger wd-35p" role="progressbar" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">35%</div>
					</div>
					<p class="tx-12 mg-b-0">Maecenas tempus, tellus eget conditum rhon.</p>
				</div>
				<!-- card -->
			</div>
			<!-- col-4 -->
		</div>
		<!-- row -->



