<?php
?>

<style>
.pulse-button {
	/*   position: relative; */
	/*   top: 50%; */
	/*   left: 50%; */
	/*   margin-left: -50px; */
	/*   margin-top: -50px; */
	/*   display: block; */
	/*   width: 100px; */
	/*   height: 100px; */
	/* 	font-size: 1.3em; */
	font-weight: light;
	font-family: 'Trebuchet MS', sans-serif;
	text-transform: uppercase;
	text-align: center;
	/* 	line-height: 100px; */
	letter-spacing: -1px;
	/*   color: white; */
	border: none;
	/*   border-radius: 50%; */
	/* 	background: #5a99d4; */
	/*   cursor: pointer; */
	/*   box-shadow: 0 0 0 0 rgba(90, 153, 212, 0.5); */
	-webkit-animation: pulse 1.5s infinite;
}

.pulse-button:hover {
	-webkit-animation: none;
}

@
-webkit-keyframes pulse { 0% {
	-moz-transform: scale(0.9);
	-ms-transform: scale(0.9);
	-webkit-transform: scale(0.9);
	transform: scale(0.9);
}
70%
{
/* -moz-transform */
:

 

scale


(1);
-ms-transform


:

 

scale


(1);
-webkit-transform


:

 

scale


(1);
transform


:

 

scale


(1);
box-shadow


:

 

0
0
0
50
px

 

rgba


(90
,
153,
212,
0);
}
100%
{
-moz-transform


:

 

scale


(0
.9


);
-ms-transform


:

 

scale


(0
.9


);
-webkit-transform


:

 

scale


(0
.9


);
transform


:

 

scale


(0
.9


);
/*     box-shadow: 0 0 0 0 rgba(90, 153, 212, 0); */
}
}
</style>
<a id="btn3" data-ajax-loader="layClaimsButton"
	class="ajax_element btn  btn-danger btn-stroke pulse-button"
	data-json='{"type":"standard"}' data-href="" style='width: 100%;'>Complete
	Profile</a>