
<div class="col-lg-12 mg-t-20 mg-lg-t-0">
	<div class="section-wrapper">
		<label class="section-title">Complete Profile</label>

		<div class="form-layout form-layout-5">
		<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<?php
echo $this->partial("user-user-profile-fieldset", array(
    "fieldset" => $form->get("userProfileFieldset")
));
?>

<div class="row mg-t-30">
				<div class="col-sm-8 mg-l-auto">
					<div class="form-layout-footer">
		
			<?php  echo $this->formsubmit($form->get("submit"))?>
			
		</div>
					<!-- form-layout-footer -->
				</div>
				<!-- col-8 -->
			</div>
<?php
echo $this->form()->closeTag();

?>
<div style="text-align: center;">
				<i id="profileaction" class="fa  fa-lg" style="display: none;"><img
					alt="" src="<?php  echo $this->basepath("/pro.gif")?>" height=27></i>
			</div>
		</div>
		
		<!-- form-layout -->
	</div>

	<!-- section-wrapper -->
</div>
<!-- col-6 -->