<?php echo $this->doctype(); ?>

<html lang="en">
<head>

<!-- Favicon-->
<!-- 		<link rel="shortcut icon" href="img/fav.png"> -->
<!-- Author Meta -->
<meta name="author" content="colorlib">
<!-- Meta Description -->
<meta name="description" content="">
<!-- Meta Keyword -->
<meta name="keywords" content="">
<!-- meta character set -->

<meta charset="utf-8">
        <?php echo $this->headTitle(' Tanim Fits '. $this->translate('Retailer'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php

echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php

echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->
        prependStylesheet($this->basePath('css/slim.css'))
            ->prependStylesheet($this->basePath('lib/Ionicons/css/ionicons.css'))
            ->prependStylesheet($this->basePath('lib/font-awesome/css/font-awesome.css'))?>

        <?php

        echo $this->headScript()
       
            ->prependFile($this->basePath('lib/jquery/js/jquery.js'))
           ?>

    </head>
<body>

	
			<?php  echo $this->content ?>
			
		

<!-- 	<script src="lib/jquery/js/jquery.js"></script> -->
	<script src="/lib/popper.js/js/popper.js"></script>
	<script src="/lib/bootstrap/js/bootstrap.js"></script>			
			
        <?php echo $this->inlineScript() ?>
    </body>
</html>
