<?php echo $this->doctype(); ?>

<html lang="en">

<head>

<!-- Favicon-->
<!-- 		<link rel="shortcut icon" href="img/fav.png"> -->
<!-- Author Meta -->
<meta name="author" content="colorlib">
<!-- Meta Description -->
<meta name="description" content="">
<!-- Meta Keyword -->
<meta name="keywords" content="">
<!-- meta character set -->

<meta charset="utf-8">
	<?php echo $this->headTitle(' Tanim Fits ' . $this->translate('Portal'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php

echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

	<!-- Le styles -->
	<?php

echo $this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico'
))
->prependStylesheet("https://cdn.jsdelivr.net/npm/vue-toast-notification/dist/theme-default.css")
    ->prependStylesheet($this->basePath('css/main.css'))
    ->prependStylesheet($this->basePath('css/owl.carousel.css'))
    ->prependStylesheet($this->basePath('css/animate.min.css'))
    ->prependStylesheet($this->basePath('css/nice-select.css'))
    ->prependStylesheet($this->basePath('css/jquery-ui.css'))
    ->prependStylesheet($this->basePath('css/magnific-popup.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.css'))
    ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
    ->prependStylesheet($this->basePath('css/linearicons.css'))
    ->prependStylesheet($this->basePath('lib/Ionicons/css/ionicons.css'))
    ->prependStylesheet($this->basePath('lib/font-awesome/css/font-awesome.css'))?>



	<?php

echo $this->headScript()
->prependFile("https://unpkg.com/sweetalert/dist/sweetalert.min.js")
->prependFile("https://cdn.jsdelivr.net/npm/vue-toast-notification")
    ->prependFile($this->basePath('js/axios.min.js'))
    ->prependFile($this->basePath('js/vue.js'))
    ->prependFile($this->basePath('wasabi/js/wasabi.gritter.js'))
    ->prependFile($this->basePath('wasabi/js/wasabi.suggest.js'))
    ->prependFile($this->basePath('wasabi/js/wasabilib.min.js'))
    ->prependFile($this->basePath('lib/jquery/js/jquery.js'))?>



</head>

<body>

	<header id="header">
		<div class="container main-menu">
			<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
					<a href="index.html"><img src="img/logo.png" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li><a href="index.html">Home</a></li>
						<li><a href="about.html">About</a></li>
						<li><a href="services.html">Services</a></li>
						<li><a href="portfolio.html">Portfolio</a></li>
						<li><a href="price.html">Pricing</a></li>
						<li class="menu-has-children"><a href="">Blog</a>
							<ul>
								<li><a href="blog-home.html">Blog Home</a></li>
								<li><a href="blog-single.html">Blog Single</a></li>
							</ul></li>
						<li class="menu-has-children"><a href="">Pages</a>
							<ul>
								<li><a href="elements.html">Elements</a></li>
								<li class="menu-has-children"><a href="">Level 2 </a>
									<ul>
										<li><a href="#">Item One</a></li>
										<li><a href="#">Item Two</a></li>
									</ul></li>
							</ul></li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav>
				<!-- #nav-menu-container -->
			</div>
		</div>
	</header>
	<!-- #header -->




	<?php echo $this->content; ?>

	<!-- start footer Area -->
	<footer class="footer-area section-gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h4>About Us</h4>
						<p>We have tested a number of registry fix and clean utilities and
							present our top 3 list on our site for your convenience.</p>
						<p class="footer-text">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;
							<script>
								document.write(new Date().getFullYear());
							</script>
							All rights reserved | This template is made with <i
								class="fa fa-heart-o" aria-hidden="true"></i> by <a
								href="http://tanimfits.com.ng" target="_blank">TANIM FITS</a>
					
					</div>
				</div>
				<div class="col-lg-5 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h4>Newsletter</h4>
						<p>Stay updated with our latest trends</p>
						<div class="" id="mc_embed_signup">
							<form target="_blank"
								action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
								method="get">
								<div class="input-group">
									<input type="text" class="form-control" name="EMAIL"
										placeholder="Enter Email Address"
										onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter Email Address '" required=""
										type="email">
									<div class="input-group-btn">
										<button class="btn btn-default" type="submit">
											<span class="lnr lnr-arrow-right"></span>
										</button>
									</div>
									<div class="info"></div>
								</div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6 social-widget">
					<div class="single-footer-widget">
						<h4>Follow Me</h4>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i
								class="fa fa-twitter"></i></a> <a href="#"><i
								class="fa fa-dribbble"></i></a> <a href="#"><i
								class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

	<script src="/js/vendor/jquery-2.2.4.min.js"></script>
	<script src="/js/popper.min.js"></script>
	<script src="/js/vendor/bootstrap.min.js"></script>
	<script
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="/js/easing.min.js"></script>
	<script src="/js/hoverIntent.js"></script>
	<script src="/js/superfish.min.js"></script>
	<script src="/js/jquery.ajaxchimp.min.js"></script>
	<script src="/js/jquery.magnific-popup.min.js"></script>
	<script src="/js/jquery.tabs.min.js"></script>
	<script src="/js/jquery.nice-select.min.js"></script>
	<script src="/js/isotope.pkgd.min.js"></script>
	<script src="/js/waypoints.min.js"></script>
	<script src="/js/jquery.counterup.min.js"></script>
	<script src="/js/simple-skillbar.js"></script>
	<script src="/js/owl.carousel.min.js"></script>
	<script src="/js/mail-script.js"></script>
	<script src="/js/main.js"></script>
	<?php echo $this->inlineScript() ?>
</body>

</html>