<?php
use General\Service\GeneralService;
$productDesc = $product->getProductDescription();
$link = $this->url("product", ["id"=>$product->getProductUid(), "name"=>GeneralService::spine($productDesc->getProductName())])
?>



<div id="product"  class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
		    				<div class="product">
		    					<a href="#" class="img-prod"><img class="img-fluid" src="<?php echo $product->getImage()[0] == NULL ? '/shop/images/no-image.png' : $product->getImage()[0]->getLowres() ?>" alt="<?php echo $this->escapehtml($productDesc->getProductName());?>">
		    						<div class="overlay"></div>
		    					</a>
		    					<div class="text py-3 px-3">
		    						<h3><a href="#"> <a href="<?php echo $link ?>"><?php echo $this->escapehtml($productDesc->getProductName());?></a></a></h3>
		    						<div class="d-flex">
		    							<div class="pricing">
				    						<p class="price"><span><?php echo $this->myCurrencyHelper($product->getPrice())?></span></p>
				    					</div>
				    					<div class="rating">
			    							<p class="text-right">
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
			    							</p>
			    						</div>
			    					</div>
		    						<p class="bottom-area d-flex px-3">
            <a @click="addToCart('<?php echo ""?>')" class="add-to-cart text-center py-2 mr-1"><span>Add to
                    cart <i class="ion-ios-add ml-1"></i>
                </span></a> <a href="<?php echo $link ?>" class="buy-now text-center py-2">View<span><i class="fa fa-fa-eye"></i></span>
            </a>
        </p>
		    					</div>
		    				</div>
		    			</div>
		    			
		    			
		    			
		    			
