<html>
  
  <head>
    <title></title>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap"
    rel="stylesheet">
    <style>
      h1 {
        margin: auto;
        font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
        text-align: center;
        font-size: 38px;
        color: #232836;
        font-weight: 700;
      }
      
      h2 {
        margin: auto;
        font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
        text-align: center;
        font-size: 24px;
        color: #232836;
        font-weight: 700;
      }
      
      h3 {
        margin: auto;
        font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
        text-align: center;
        font-size: 20px;
        color: #232836;
        font-weight: 500;
      }
      
      p, ul {
        margin: auto;
        font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
        text-align: left;
        font-size:  16px;
        color: #232836;
        font-weight: 400;
      }
      
      a {
        color:#0171D3;
      }
      
      img {
        display: block;
      }
      
      .ellipsis {
        text-overflow: ellipsis;
      }
      
      .background-email {
        max-width: 512px;
        background-color: #F0F9FF;
        margin: auto;
        padding:40px 48px 64px 48px;
        border-radius: 16px;
      }
      
      .background-button {
        display: block;
        margin: auto;
        max-width: 320px;
        background-color: #0171D3;
        padding: 16px;
        border-radius: 8px;
        text-decoration: none;
      }
      
      .label-button {
        display: block;
        margin: auto;
        font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
        text-align: center;
        font-size: 16px;
        color: #FFFFFF;
        font-weight: 500;
      }
      
      .text-center {
        text-align: center;
      }
      
      .flex-container-icon-left {
        display: flex;
        margin-bottom: 64px;
        align-items: flex-start;
        align-content: flex-start;
      }
      
      .icon-left {
        width: 72px;
        min-width: 72px;
        max-width: 72px;
      }
      
      @media only screen and (max-width: 600px) {
      
        .background-email {
          max-width: 512px;
          background-color: #F0F9FF;
          margin: auto;
          padding:20px 24px 32px 24px;
          border-radius: 16px;
        }
      
        .flex-container-icon-left {
          display: flex;
          flex-direction: column;
          margin-bottom: 64px;
          justify-content: center;
          align-items: center;
        }
      
        .icon-left {
          width: 72px;
          min-width: 72px;
          max-width: 72px;
          padding-bottom: 24px;
          align-self: baseline;
        }
      
        h1 {
          margin: auto;
          font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
          text-align: center;
          font-size: 28px;
          color: #232836;
          font-weight: 700;
        }
      
        p {
          margin: auto;
          font-family: 'Manrope', -apple-system, helvetica, arial, sans-serif;
          text-align: left;
          font-size:  14px;
          color: #232836;
          font-weight: 400;
        }
      }
    </style>
  </head>
  
  <body>
    <div class="background-email" width="100%">
      <img src="http://localhost:2003/img/logo.png"
      style="max-width: 170px; margin: auto; margin-bottom:88px;" width="100%">
       <h1 style="margin-bottom:40px;" width="100%">
   Great Job !
  </h1>

      <img src="https://c4.wallpaperflare.com/wallpaper/805/538/482/sunset-4k-download-hd-wallpaper-preview.jpg"
      class="text-center" style="max-width: 490px; margin: auto; margin-bottom:64px;"
      width="100%">
       <h2 style="margin-bottom:40px;" width="100%">
    You just submitted your assignments and milestones 
  </h2>

       

      
      <p class="text-center" style="margin-bottom:64px;" width="100%">Next step includes:
        
      </p>
       

      
       <h3 style="margin-bottom:40px;"
      width="100%">
    Privacy policy
  </h3>

      <div class="flex-container-icon-left" width="100%">
        <div>
          <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/79edda7b-89af-4bd7-ae7d-d8ddc6975c67/144x188.png"
          class="icon-left">
        </div>
        <p>
          <ul>
            <li>In order to use Honeygain we will need your Email address, Device and Network
              info and Payment info (for the payout).</li>
            <br>
            <li>Our website collects cookies</li>
            <br>
            <li>We comply to the GDPR, CCPA and other legislations.</li>
            <br>
            <li>If you have any questions on your Data security - contact us at
              <a href="mailto:legal@honeygain.com"
              target="_blank">legal@honeygain.com</a>
            </li>
          </ul>
        </p>
      </div>
       <h3 style="margin-bottom:40px;" width="100%">
      Terms of Use
  </h3>

      <div class="flex-container-icon-left" width="100%">
        <div>
          <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/9b1c1bc8-f5a2-4f53-b5ad-045ba7064fd3/144x188.png"
          class="icon-left">
        </div>
        <p>
          <ul>
            <li>Honeygain has two ways to earn money:
              <br>
              <br>1. Network Sharing - used for web and market analytics, SEO monitoring, brand
              protection, etc. - calculated by the amount of data shared.
              <br>
              <br>2. Content Delivery - used for more bandwidth intensive content like, videos,
              audio, streaming services etc - calculated by the time it's active.</li>
            <br>
            <li>We restrict and penalise users for attempts to modify our apps, fraud, game, cheat
              or interfere with Honeygain's operation.</li>
          </ul>
        </p>
      </div>
      <p class="text-center" style="margin-bottom:64px;" width="100%">Ok, now that's done. Let's continue through the checklist.</p>
       <h2 style="margin-bottom:64px;"
      width="100%">
    So, how to use Honeygain?
  </h2>

      <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/1f6b49fa-ce3a-4303-b5cb-83c8ee58c538/638x522.png"
      class="text-center" style="max-width: 320px; margin: auto; margin-bottom:40px;"
      width="100%">
       <h3 style="margin-bottom:40px;" width="100%">
      First step to start earning - Install the App
  </h3>

      <p style="margin-bottom:40px;" width="100%">To start earning with Honeygain you need to install Honeygain on your devices.
        You can do that on Windows, macOS or Android devices. Just go to the download page
        and install the app!</p>
      <a href="https://www.honeygain.com/download/?utm_medium=Welcome&utm_source=Mailer"
      class="background-button" style="margin-bottom:40px;" width="100%" target="_blank"> <span class="label-button">Download Honeygain</span>

      </a>
      <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/8f178ff4-d317-4059-bbd0-3c16c6dbf73b/576x144.png"
      class="text-center" style="max-width: 192px; margin: auto; margin-bottom:8px;"
      width="100%">
      <p class="text-center" style="font-size: 12px; margin-bottom:64px;" width="100%">Available on Windows, MacOS and Android</p>
      <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/d8e299b1-6e52-48a9-b88a-da237d36cd4e/1247x594.png"
      class="text-center" style="max-width: 446px; margin: auto; margin-bottom:40px;"
      width="100%">
       <h3 style="margin-bottom:40px;" width="100%">
      -OK. What now?<br>-Start sharing your network connection!
  </h3>

      <p style="margin-bottom:40px;" width="100%">Make sure your devices are connected to the internet and the app is running. To
        further increase your earnings - connect more devices and enable Content Delivery*
        <br>
        <br>*Available in a limited number of Countries
        <br>You can read more about how your internet is used on
        <a href="https://www.honeygain.com/blog/?utm_medium=Welcome&utm_source=Mailer"
        target="_blank">our blog</a>.</p>
      <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/0f282d3e-c0f6-45e7-be3b-1f8b40ff2c92/664x454.png"
      class="text-center" style="max-width: 332px; margin: auto; margin-bottom:40px;"
      width="100%">
       <h3 style="margin-bottom:40px;" width="100%">
      How will I get paid?
  </h3>

      <p style="margin-bottom:64px;" width="100%">You will get paid through your PayPal account. Other options are on their way!
        <br>
        <br>The only thing to note is that the minimum payout is $20.</p>
       <h2 style="margin-bottom:40px;"
      width="100%">
    So, what are you waiting for?
  </h2>

      <p class="text-center" style="margin-bottom:48px;" width="100%">Sign in, turn on Honeygain and watch the money flow!
        <br>
        <br>We're looking forward to paying you!</p>
      <p class="text-center" style="margin-bottom:64px;"
      width="100%">If this still left you questions, check out our
        <a href="https://honeygain.zendesk.com/hc/en-us"
        target="_blank">Helpdesk</a> or reach us at
        <a href="mailto:support@honeygain.com" target="_blank">support@honeygain.com</a>
      </p>
      <p class="text-center" style="margin-bottom:24px;" width="100%">Don't forget to follow us on social media:</p>
      <div style="display: flex; justify-content: space-between; width: 138px; height: 32px; margin: 0 auto; margin-bottom: 64px;">
        <div>
          <a href="https://www.instagram.com/accounts/login/" style="text-decoration: none;"
          target="_blank">
            <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/e4b448c6-fa4c-4622-9e8f-df13a4a3794a/64x64.png"
            class="text-center" style="width: 32px;" width="100%">
          </a>
        </div>
        <div>
          <a href="https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fhoneygainapp%2F"
          style="text-decoration: none;" target="_blank">
            <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/f41166e7-5c20-4d4b-afdc-5ed37f6611ee/64x64.png"
            class="text-center" style="width: 32px;" width="100%">
          </a>
        </div>
        <a href="https://twitter.com/honeygain_app/" style="text-decoration: none;" target="_blank">
          <img src="http://cdn.mcauto-images-production.sendgrid.net/acf8df57c31b4432/c984fdd6-53a6-4f3f-b824-323125e40f29/64x64.png"
          class="text-center" style="width: 32px;" width="100%">
        </a>
      </div>
      <p class="text-center" width="100%">With love️
        <br>Honeygain team</p>
    </div>

  </body>

</html>