<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
 <h6 class="slim-card-title mg-b-20">Open a support ticket</h6>
<?php
echo $this->partial("support-fieldset", array("fieldset"=>$form->get("supportFieldset")));
?>
<?php 
echo $this->formsubmit($form->get("submit"));
echo $this->form()->closeTag();
?>

<div style="text-align: center;">
						<i id="submitTicket" class="fa  fa-lg" style="display: none;"><img
							alt="" src="<?php  echo $this->basepath("/pro.gif")?>"
							height=27></i>
					</div>