<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Support\Module'                        => __DIR__ . '/Module.php',
    'Support\Controller\SupportController' => __DIR__ . '/src/Support/Controller/SupportController.php',
    'SupportTest\Framework\TestCase'        => __DIR__ . '/tests/Support/Framework/TestCase.php',
    'SupportTest\SampleTest'                => __DIR__ . '/tests/Support/SampleTest.php',
);
