<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bbmin\Module'                        => __DIR__ . '/Module.php',
    'Bbmin\Controller\BbminController' => __DIR__ . '/src/Bbmin/Controller/BbminController.php',
    'BbminTest\Framework\TestCase'        => __DIR__ . '/tests/Bbmin/Framework/TestCase.php',
    'BbminTest\SampleTest'                => __DIR__ . '/tests/Bbmin/SampleTest.php',
);
