<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Transaction\Module'                        => __DIR__ . '/Module.php',
    'Transaction\Controller\TransactionController' => __DIR__ . '/src/Transaction/Controller/TransactionController.php',
    'TransactionTest\Framework\TestCase'        => __DIR__ . '/tests/Transaction/Framework/TestCase.php',
    'TransactionTest\SampleTest'                => __DIR__ . '/tests/Transaction/SampleTest.php',
);
