<?php ?>

<div class="card card-people-list">
	<div class="slim-card-title">Resources</div>
	<?php if(count($data) > 0):?>
	<div class="media-list">
	<?php foreach ( $data as $dat):?>
		<div class="media">
			<?php  echo $this->fileIconViewHelper($dat['document']["mimeType"])?>
			<div class="media-body">
				<a href=""><?php  echo $dat['name'] ?></a>
				<p><?php  echo $dat['document']["mimeType"]?></p>
			</div>
			<!-- media-body -->
			<a href="<?php  echo $dat['document']['imageUrl']?>" target="_blank"><i
				class="icon ion-eye tx-20"></i></a>
		</div>
		<!-- media -->

	
	<?php
    endforeach;
    ?>
    </div>
<?php else :
    ?>
	<h5>No Resource available</h5>
	<?php
endif;
?>
	<!-- media-list -->
</div>
<!-- card -->

