
<div id="dropzone"><?php
$dropzoneform->prepare();
echo $this->form()->openTag($dropzoneform);
?>
<div class="dz-message needsclick">
      Drop files <b>here</b> or <b>click</b> to upload.<br />
      <span class="dz-note needsclick">
<!--         (This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.) -->
      </span>
    </div>
<?php 
echo $this->form()->closeTag();
?>
</div>

<?php  echo $this->headlink()->appendStylesheet("/admin/assets/plugins/dropzone/min/dropzone.min.css")?>

