<?php
echo $this->headtitle("About Retailer: TFITS.ONLINE");
?>

<div class="hero-wrap hero-bread"
	style="background-image: url('/shop/images/bg_6.jpg');">
	<div class="container">
		<div
			class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs">
					<span class="mr-2"><a href="index.html">Home</a></span> <span>About</span>
				</p>
				<h1 class="mb-0 bread">About Us</h1>
			</div>
		</div>
	</div>
</div>





<!-- 				https://vimeo.com/45830194 -->

<section class="ftco-section ftco-no-pb ftco-no-pt bg-light">
	<div class="container">
		<div class="row">
			<div
				class="col-md-5 p-md-5 img img-2 d-flex justify-content-center align-items-center"
				style="background-image: url(images/about.jpg);">
				<a href=""

					class="icon popup-vimeo d-flex justify-content-center align-items-center">
					<span class="icon-play"></span>
				</a>
			</div>
			<div class="col-md-7 py-5 wrap-about pb-md-5 ftco-animate">
				<div class="heading-section-bold mb-4 mt-md-5">
					<div class="ml-md-0">
						<h2 class="mb-4">Empowering the African Woman</h2>
					</div>
				</div>
				<div class="pb-md-5">
					<p>Tanim Fits address gender digital divide, by using a multi level
						reward based system to empower enlighten and network the African
						woman, via a web based portal. We do this by empowering women with
						credit usable only on our web application as retailers, but most
						of all provide them with digital tools and knowledge that enhances
						a digital commercial lifestyle, thereby increasing their digital
						knowledge and embracing such lifestyle.</p>
					<div class="row ftco-services">
						<div
							class="col-lg-4 text-center d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services">
								<div
									class="icon d-flex justify-content-center align-items-center mb-4">
									<span class="flaticon-002-recommended"></span>
								</div>
								<div class="media-body">
									<h3 class="heading">Refund Policy</h3>
									<p>We have a smooth and user friendly refund policy that cuts accross </p>
								</div>
							</div>
						</div>
						<div
							class="col-lg-4 text-center d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services">
								<div
									class="icon d-flex justify-content-center align-items-center mb-4">
									<span class="flaticon-001-box"></span>
								</div>
								<div class="media-body">
									<h3 class="heading">Digital Tools</h3>
									<p>We provide digital tool toa assist you in sales </p>
								</div>
							</div>
						</div>
						<div
							class="col-lg-4 text-center d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services">
								<div
									class="icon d-flex justify-content-center align-items-center mb-4">
									<span class="flaticon-003-medal"></span>
								</div>
								<div class="media-body">
									<h3 class="heading">Reward Based System</h3>
									<p>Every action taken on our platform is accompanied by a reward</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>