<?php
echo $this->headtitle(($category->getCategory() ??  "") . " Product Category");
// var_dump($products);
//define a category Helper
?>

<div class="hero-wrap hero-bread" style="background-image: url('<?= $category->getImage()->getImageUrl() ?>');">
	<div class="container">
		<div class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs">
					<span class="mr-2"><a href="">Home</a></span> <span>About</span>
				</p>
				<h1 class="mb-0 bread">About Us</h1>
			</div>
		</div>
	</div>
</div>

<section class="ftco-section bg-light">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-lg-10 order-md-last">
				<div class="row">

					
						<?php foreach ($products as $product):
						?>
						<?php echo $this->partial("shop_product_thumbnail_snippet", ["product"=>$product])
						?>
						<?php endforeach;
						?>
				



				</div>
				
			</div>

			<div id="categoryList" class="col-md-4 col-lg-2 sidebar">
				<div v-if="category.length" class="sidebar-box-2">
					<h2 class="heading mb-4"><a href="#">Shop Category</a></h2>
					<ul>
						<li v-for="cat in category"><a :href="displayCategoryLink(cat)">{{cat.category}}</a></li>
					</ul>
				</div>
				<!-- <div class="sidebar-box-2">
		    			<h2 class="heading mb-4"><a href="#">Jeans</a></h2>
		    			<ul>
		    				<li><a href="#">Shirts &amp; Tops</a></li>
								<li><a href="#">Dresses</a></li>
								<li><a href="#">Shorts &amp; Skirts</a></li>
								<li><a href="#">Jackets</a></li>
								<li><a href="#">Coats</a></li>
								<li><a href="#">Jeans</a></li>
								<li><a href="#">Sleeveless</a></li>
								<li><a href="#">Trousers</a></li>
								<li><a href="#">Winter Coats</a></li>
								<li><a href="#">Jumpsuits</a></li>
		    			</ul>
		    		</div> -->
				<!-- <div class="sidebar-box-2">
					<h2 class="heading mb-2"><a href="#">Bags</a></h2>
					<h2 class="heading mb-2"><a href="#">Accessories</a></h2>
				</div> -->
				<!-- <div class="sidebar-box-2">
					<h2 class="heading mb-4"><a href="#">Shoes</a></h2>
					<ul>
						<li><a href="#">Nike</a></li>
						<li><a href="#">Addidas</a></li>
						<li><a href="#">Skechers</a></li>
						<li><a href="#">Jackets</a></li>
						<li><a href="#">Coats</a></li>
						<li><a href="#">Jeans</a></li>
					</ul>
				</div> -->
			</div>
		</div>
	</div>
</section>

<script>
    let thumbnail = new Vue({
        el: "#product",
        data() {
            return {
                
             
                
                
            }
        },
        computed: {
            priceStatus(){
             if(this.isDiscount == 1){
                 return "mr-2 price-dc";
             }else{
                 return "price";
             }
            }
        },
        methods: {
            addToCart(cartUid) {
                axios.post("/").then(res=>{
                    if(res.status == 201){
                        // show notification
                    }
                });
            },

            disCountedLogic(){

            }
        },
    });
</script>
<script>
	let categoryList = new Vue({
		el: "#categoryList",
		data() {
			return {
				category: []
			}
		},
		mounted() {
			this.getCategory();
		},
		methods: {
			getCategory() {
				axios.get("/shopajax/get-shop-category").then(res => {
					if (res.status == 200) {
						this.category = res.data.category
					}
				});
			},

			displayCategoryLink(cat) {
				return "/cat/" + cat.id + "/" + cat.slug
			}
		},
	});
</script>