<?php

use General\Service\GeneralService;

echo $this->headtitle("Contact Retailer: TFITS.ONLINE");
?>
<div id="contacts"></div>
<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
	<div class="container">
		<div class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs">
					<span class="mr-2"><a href="index.html">Home</a></span> <span>Contact</span>
				</p>
				<h1 class="mb-0 bread">Contact Us</h1>
			</div>
		</div>
	</div>
</div>

<section class="ftco-section contact-section bg-light">
	<div class="container">
		<div class="row d-flex mb-5 contact-info">
			<div class="w-100"></div>
			<div class="col-md-3 d-flex">
				<div class="info bg-white p-4">
					<p>
						<span>Address:</span> <?php echo GeneralService::COMPANY_ADDRESS ?>
					</p>
				</div>
			</div>
			<div class="col-md-3 d-flex">
				<div class="info bg-white p-4">
					<p>
						<span>Phone:</span> <a href="tel://" .<?php GeneralService::COMPANY_PHONE ?>><?php echo GeneralService::COMPANY_PHONE ?></a>
					</p>
				</div>
			</div>
			<div class="col-md-3 d-flex">
				<div class="info bg-white p-4">
					<p>
						<span>Email:</span> <a href="mailto:info@yoursite.com"><?php echo GeneralService::COMPANY_EMAIL ?></a>
					</p>
				</div>
			</div>
			<div class="col-md-3 d-flex">
				<div class="info bg-white p-4">
					<p>
						<span>Website</span> <a href="#"><?php echo GeneralService::COMPANY_URL ?></a>
					</p>
				</div>
			</div>
		</div>
		<div class="row block-9">
			<div class="col-md-6 order-md-last d-flex">
				<form action="#" class="bg-white p-5 contact-form">
					<div class="form-group">
						<input type="text" ref="contactname" class="form-control" placeholder="Your Name">
					</div>
					<div class="form-group">
						<input type="text" ref="contactemail" class="form-control" placeholder="Your Email">
					</div>
					<div class="form-group">
						<input type="text" ref="contactsubject" class="form-control" placeholder="Subject">
					</div>
					<div class="form-group">
						<textarea name="" ref="contactmessage" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
					</div>
					<div class="form-group">
						<button @click="contactus()" type="submit" value="Send Message" class="btn btn-primary py-3 px-5"></button>
					</div>
				</form>

			</div>

			<div class="col-md-6 d-flex">
				<div id="map" class="bg-white"></div>
			</div>
		</div>
	</div>
</section>


<script>
	let contacts = new Vue({
		el: '#contacts',
		data() {
			return {
				status: false,
				message: '',
				email: '',
				subject: '',
				name: '',
			}
		},

		methods: {
			contactus() {
				if (this.$refs.contactname.value == '' || this.$refs.contactemail.value || this.$refs.contactsubject.value || this.$refs.contactmessage.value) {

					swal({
						title: "ERROR",
						text: "You have forgotten to fill a required form",
						icon: "error",
						button: "OK"
					});
				} else {
					let formData = new FormData();
					formData.append('name', this.$refs.contactname.value);
					formData.append('email', this.$refs.contactemail.value);
					formData.append('subject', this.$refs.contactsubject.value);
					formData.append('message', this.$refs.contactmessage.value);
					axios.post('/appmodal/contactusmodal', formData).then(res => {
						if (res.status == 201) {
							swal({
								title: "Support Notified",
								text: "Our customer service has benn notified of your request ",
								icon: "success",
								button: "Continue!",
							}).then(res => {
								this.status = true;
								this.$refs.contactname.value = '';
								this.$refs.contactemail.value = '';
								this.$refs.contactsubject.value = '';
							});


						}
					}).catch(err => {
						swal({
							title: "ERROR",
							text: err.response.data.messages,
							icon: "error",
							button: "OK"
						});
					});
				}
			}
		},
	})
</script>