<?php
echo $this->headtitle("Return policy");

?>

<div class="hero-wrap hero-bread"
	style="background-image: url('/shop/images/bg_6.jpg');">
	<div class="container">
		<div
			class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs">
					<span class="mr-2"><a href="">Home</a></span> <span>Return Policy</span>
				</p>
				<h1 class="mb-0 bread">Return Policy</h1>
			</div>
		</div>
	</div>
</div>







<section class="ftco-section ftco-no-pb ftco-no-pt bg-light">
	<div class="container">
		<div class="row">
			<div
				class="col-md-5 p-md-5 img img-2 d-flex justify-content-center align-items-center"
				style="background-image: url(images/about.jpg);">
				<a href=""
					class="icon popup-vimeo d-flex justify-content-center align-items-center">
					<span class="icon-play"></span>
				</a>
			</div>
			<div class="col-md-7 py-5 wrap-about pb-md-5 ftco-animate">
				<div class="heading-section-bold mb-4 mt-md-5">
					<div class="ml-md-0">
						<h2 class="mb-4">WHAT IS TANIM FITS'S RETURNS POLICY?</h2>
					</div>
				</div>
				<div class="pb-md-5">
					TEMPORARY RETURN EXTENSION All
						<p> TANIM FITS purchases have an
						extended 10-day returns policy (some exceptions apply). We design
						our garment to help you tell a story, so if they're not working
						exactly right for you, we've got you covered. When you shop on
						TANIM FITS online shop or in the MOBILE APP, we give you 10 days
						to take your purchases for a trial run, confidently knowing you
						can return items (some exceptions apply) for any reason within
						those 10 days. That includes custom garments. Even after 10 days,
						you can still return items if they're unworn and unwashed. And
						remember, returns are always free for members.<br> When you shop in
						TANIM FITS stores, you'll also have 10 days to return your
						purchase for any reason. Please note that your items must be
						unworn and unwashed to be able to return them.</p>
					<div class="row ftco-services">
					
						</div>
				</div>
			</div>
		</div>
	</div>
</section>

